///////////////////////////////////////////////////////////////////////////////
//
//  The contents of this file are subject to the Mozilla Public License
//  Version 1.1 (the "License"); you may not use this file except in
//  compliance with the License. You may obtain a copy of the License at
//  http://www.mozilla.org/MPL/
//
//  Software distributed under the License is distributed on an "AS IS"
//  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
//  License for the specific language governing rights and limitations
//  under the License.
// 
//  The Original Code is MP4v2.
// 
//  The Initial Developer of the Original Code is Kona Blend.
//  Portions created by Kona Blend are Copyright (C) 2008.
//  All Rights Reserved.
//
//  Contributors:
//      Kona Blend, kona8lend@@gmail.com
//
///////////////////////////////////////////////////////////////////////////////

#include "impl.h"

namespace mp4v2 { namespace impl {

///////////////////////////////////////////////////////////////////////////////

template <>
const bmff::EnumLanguageCode::Entry bmff::EnumLanguageCode::data[] = {
    { mp4v2::impl::bmff::ILC_AAR,  "aar",  "Afar" },
    { mp4v2::impl::bmff::ILC_ABK,  "abk",  "Abkhazian" },
    { mp4v2::impl::bmff::ILC_ACE,  "ace",  "Achinese" },
    { mp4v2::impl::bmff::ILC_ACH,  "ach",  "Acoli" },
    { mp4v2::impl::bmff::ILC_ADA,  "ada",  "Adangme" },
    { mp4v2::impl::bmff::ILC_ADY,  "ady",  "Adyghe; Adygei" },
    { mp4v2::impl::bmff::ILC_AFA,  "afa",  "Afro-Asiatic (Other)" },
    { mp4v2::impl::bmff::ILC_AFH,  "afh",  "Afrihili" },
    { mp4v2::impl::bmff::ILC_AFR,  "afr",  "Afrikaans" },
    { mp4v2::impl::bmff::ILC_AIN,  "ain",  "Ainu" },
    { mp4v2::impl::bmff::ILC_AKA,  "aka",  "Akan" },
    { mp4v2::impl::bmff::ILC_AKK,  "akk",  "Akkadian" },
    { mp4v2::impl::bmff::ILC_SQI,  "sqi",  "Albanian" },
    { mp4v2::impl::bmff::ILC_ALE,  "ale",  "Aleut" },
    { mp4v2::impl::bmff::ILC_ALG,  "alg",  "Algonquian languages" },
    { mp4v2::impl::bmff::ILC_ALT,  "alt",  "Southern Altai" },
    { mp4v2::impl::bmff::ILC_AMH,  "amh",  "Amharic" },
    { mp4v2::impl::bmff::ILC_ANG,  "ang",  "English, Old (ca.450-1100)" },
    { mp4v2::impl::bmff::ILC_ANP,  "anp",  "Angika" },
    { mp4v2::impl::bmff::ILC_APA,  "apa",  "Apache languages" },
    { mp4v2::impl::bmff::ILC_ARA,  "ara",  "Arabic" },
    { mp4v2::impl::bmff::ILC_ARC,  "arc",  "Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)" },
    { mp4v2::impl::bmff::ILC_ARG,  "arg",  "Aragonese" },
    { mp4v2::impl::bmff::ILC_HYE,  "hye",  "Armenian" },
    { mp4v2::impl::bmff::ILC_ARN,  "arn",  "Mapudungun; Mapuche" },
    { mp4v2::impl::bmff::ILC_ARP,  "arp",  "Arapaho" },
    { mp4v2::impl::bmff::ILC_ART,  "art",  "Artificial (Other)" },
    { mp4v2::impl::bmff::ILC_ARW,  "arw",  "Arawak" },
    { mp4v2::impl::bmff::ILC_ASM,  "asm",  "Assamese" },
    { mp4v2::impl::bmff::ILC_AST,  "ast",  "Asturian; Bable; Leonese; Asturleonese" },
    { mp4v2::impl::bmff::ILC_ATH,  "ath",  "Athapascan languages" },
    { mp4v2::impl::bmff::ILC_AUS,  "aus",  "Australian languages" },
    { mp4v2::impl::bmff::ILC_AVA,  "ava",  "Avaric" },
    { mp4v2::impl::bmff::ILC_AVE,  "ave",  "Avestan" },
    { mp4v2::impl::bmff::ILC_AWA,  "awa",  "Awadhi" },
    { mp4v2::impl::bmff::ILC_AYM,  "aym",  "Aymara" },
    { mp4v2::impl::bmff::ILC_AZE,  "aze",  "Azerbaijani" },
    { mp4v2::impl::bmff::ILC_BAD,  "bad",  "Banda languages" },
    { mp4v2::impl::bmff::ILC_BAI,  "bai",  "Bamileke languages" },
    { mp4v2::impl::bmff::ILC_BAK,  "bak",  "Bashkir" },
    { mp4v2::impl::bmff::ILC_BAL,  "bal",  "Baluchi" },
    { mp4v2::impl::bmff::ILC_BAM,  "bam",  "Bambara" },
    { mp4v2::impl::bmff::ILC_BAN,  "ban",  "Balinese" },
    { mp4v2::impl::bmff::ILC_EUS,  "eus",  "Basque" },
    { mp4v2::impl::bmff::ILC_BAS,  "bas",  "Basa" },
    { mp4v2::impl::bmff::ILC_BAT,  "bat",  "Baltic (Other)" },
    { mp4v2::impl::bmff::ILC_BEJ,  "bej",  "Beja; Bedawiyet" },
    { mp4v2::impl::bmff::ILC_BEL,  "bel",  "Belarusian" },
    { mp4v2::impl::bmff::ILC_BEM,  "bem",  "Bemba" },
    { mp4v2::impl::bmff::ILC_BEN,  "ben",  "Bengali" },
    { mp4v2::impl::bmff::ILC_BER,  "ber",  "Berber (Other)" },
    { mp4v2::impl::bmff::ILC_BHO,  "bho",  "Bhojpuri" },
    { mp4v2::impl::bmff::ILC_BIH,  "bih",  "Bihari" },
    { mp4v2::impl::bmff::ILC_BIK,  "bik",  "Bikol" },
    { mp4v2::impl::bmff::ILC_BIN,  "bin",  "Bini; Edo" },
    { mp4v2::impl::bmff::ILC_BIS,  "bis",  "Bislama" },
    { mp4v2::impl::bmff::ILC_BLA,  "bla",  "Siksika" },
    { mp4v2::impl::bmff::ILC_BNT,  "bnt",  "Bantu (Other)" },
    { mp4v2::impl::bmff::ILC_BOS,  "bos",  "Bosnian" },
    { mp4v2::impl::bmff::ILC_BRA,  "bra",  "Braj" },
    { mp4v2::impl::bmff::ILC_BRE,  "bre",  "Breton" },
    { mp4v2::impl::bmff::ILC_BTK,  "btk",  "Batak languages" },
    { mp4v2::impl::bmff::ILC_BUA,  "bua",  "Buriat" },
    { mp4v2::impl::bmff::ILC_BUG,  "bug",  "Buginese" },
    { mp4v2::impl::bmff::ILC_BUL,  "bul",  "Bulgarian" },
    { mp4v2::impl::bmff::ILC_MYA,  "mya",  "Burmese" },
    { mp4v2::impl::bmff::ILC_BYN,  "byn",  "Blin; Bilin" },
    { mp4v2::impl::bmff::ILC_CAD,  "cad",  "Caddo" },
    { mp4v2::impl::bmff::ILC_CAI,  "cai",  "Central American Indian (Other)" },
    { mp4v2::impl::bmff::ILC_CAR,  "car",  "Galibi Carib" },
    { mp4v2::impl::bmff::ILC_CAT,  "cat",  "Catalan; Valencian" },
    { mp4v2::impl::bmff::ILC_CAU,  "cau",  "Caucasian (Other)" },
    { mp4v2::impl::bmff::ILC_CEB,  "ceb",  "Cebuano" },
    { mp4v2::impl::bmff::ILC_CEL,  "cel",  "Celtic (Other)" },
    { mp4v2::impl::bmff::ILC_CHA,  "cha",  "Chamorro" },
    { mp4v2::impl::bmff::ILC_CHB,  "chb",  "Chibcha" },
    { mp4v2::impl::bmff::ILC_CHE,  "che",  "Chechen" },
    { mp4v2::impl::bmff::ILC_CHG,  "chg",  "Chagatai" },
    { mp4v2::impl::bmff::ILC_ZHO,  "zho",  "Chinese" },
    { mp4v2::impl::bmff::ILC_CHK,  "chk",  "Chuukese" },
    { mp4v2::impl::bmff::ILC_CHM,  "chm",  "Mari" },
    { mp4v2::impl::bmff::ILC_CHN,  "chn",  "Chinook jargon" },
    { mp4v2::impl::bmff::ILC_CHO,  "cho",  "Choctaw" },
    { mp4v2::impl::bmff::ILC_CHP,  "chp",  "Chipewyan; Dene Suline" },
    { mp4v2::impl::bmff::ILC_CHR,  "chr",  "Cherokee" },
    { mp4v2::impl::bmff::ILC_CHU,  "chu",  "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic" },
    { mp4v2::impl::bmff::ILC_CHV,  "chv",  "Chuvash" },
    { mp4v2::impl::bmff::ILC_CHY,  "chy",  "Cheyenne" },
    { mp4v2::impl::bmff::ILC_CMC,  "cmc",  "Chamic languages" },
    { mp4v2::impl::bmff::ILC_COP,  "cop",  "Coptic" },
    { mp4v2::impl::bmff::ILC_COR,  "cor",  "Cornish" },
    { mp4v2::impl::bmff::ILC_COS,  "cos",  "Corsican" },
    { mp4v2::impl::bmff::ILC_CPE,  "cpe",  "Creoles and pidgins, English based (Other)" },
    { mp4v2::impl::bmff::ILC_CPF,  "cpf",  "Creoles and pidgins, French-based (Other)" },
    { mp4v2::impl::bmff::ILC_CPP,  "cpp",  "Creoles and pidgins, Portuguese-based (Other)" },
    { mp4v2::impl::bmff::ILC_CRE,  "cre",  "Cree" },
    { mp4v2::impl::bmff::ILC_CRH,  "crh",  "Crimean Tatar; Crimean Turkish" },
    { mp4v2::impl::bmff::ILC_CRP,  "crp",  "Creoles and pidgins (Other)" },
    { mp4v2::impl::bmff::ILC_CSB,  "csb",  "Kashubian" },
    { mp4v2::impl::bmff::ILC_CUS,  "cus",  "Cushitic (Other)" },
    { mp4v2::impl::bmff::ILC_CES,  "ces",  "Czech" },
    { mp4v2::impl::bmff::ILC_DAK,  "dak",  "Dakota" },
    { mp4v2::impl::bmff::ILC_DAN,  "dan",  "Danish" },
    { mp4v2::impl::bmff::ILC_DAR,  "dar",  "Dargwa" },
    { mp4v2::impl::bmff::ILC_DAY,  "day",  "Land Dayak languages" },
    { mp4v2::impl::bmff::ILC_DEL,  "del",  "Delaware" },
    { mp4v2::impl::bmff::ILC_DEN,  "den",  "Slave (Athapascan)" },
    { mp4v2::impl::bmff::ILC_DGR,  "dgr",  "Dogrib" },
    { mp4v2::impl::bmff::ILC_DIN,  "din",  "Dinka" },
    { mp4v2::impl::bmff::ILC_DIV,  "div",  "Divehi; Dhivehi; Maldivian" },
    { mp4v2::impl::bmff::ILC_DOI,  "doi",  "Dogri" },
    { mp4v2::impl::bmff::ILC_DRA,  "dra",  "Dravidian (Other)" },
    { mp4v2::impl::bmff::ILC_DSB,  "dsb",  "Lower Sorbian" },
    { mp4v2::impl::bmff::ILC_DUA,  "dua",  "Duala" },
    { mp4v2::impl::bmff::ILC_DUM,  "dum",  "Dutch, Middle (ca.1050-1350)" },
    { mp4v2::impl::bmff::ILC_NLD,  "nld",  "Dutch; Flemish" },
    { mp4v2::impl::bmff::ILC_DYU,  "dyu",  "Dyula" },
    { mp4v2::impl::bmff::ILC_DZO,  "dzo",  "Dzongkha" },
    { mp4v2::impl::bmff::ILC_EFI,  "efi",  "Efik" },
    { mp4v2::impl::bmff::ILC_EGY,  "egy",  "Egyptian (Ancient)" },
    { mp4v2::impl::bmff::ILC_EKA,  "eka",  "Ekajuk" },
    { mp4v2::impl::bmff::ILC_ELX,  "elx",  "Elamite" },
    { mp4v2::impl::bmff::ILC_ENG,  "eng",  "English" },
    { mp4v2::impl::bmff::ILC_ENM,  "enm",  "English, Middle (1100-1500)" },
    { mp4v2::impl::bmff::ILC_EPO,  "epo",  "Esperanto" },
    { mp4v2::impl::bmff::ILC_EST,  "est",  "Estonian" },
    { mp4v2::impl::bmff::ILC_EWE,  "ewe",  "Ewe" },
    { mp4v2::impl::bmff::ILC_EWO,  "ewo",  "Ewondo" },
    { mp4v2::impl::bmff::ILC_FAN,  "fan",  "Fang" },
    { mp4v2::impl::bmff::ILC_FAO,  "fao",  "Faroese" },
    { mp4v2::impl::bmff::ILC_FAT,  "fat",  "Fanti" },
    { mp4v2::impl::bmff::ILC_FIJ,  "fij",  "Fijian" },
    { mp4v2::impl::bmff::ILC_FIL,  "fil",  "Filipino; Pilipino" },
    { mp4v2::impl::bmff::ILC_FIN,  "fin",  "Finnish" },
    { mp4v2::impl::bmff::ILC_FIU,  "fiu",  "Finno-Ugrian (Other)" },
    { mp4v2::impl::bmff::ILC_FON,  "fon",  "Fon" },
    { mp4v2::impl::bmff::ILC_FRA,  "fra",  "French" },
    { mp4v2::impl::bmff::ILC_FRM,  "frm",  "French, Middle (ca.1400-1600)" },
    { mp4v2::impl::bmff::ILC_FRO,  "fro",  "French, Old (842-ca.1400)" },
    { mp4v2::impl::bmff::ILC_FRR,  "frr",  "Northern Frisian" },
    { mp4v2::impl::bmff::ILC_FRS,  "frs",  "Eastern Frisian" },
    { mp4v2::impl::bmff::ILC_FRY,  "fry",  "Western Frisian" },
    { mp4v2::impl::bmff::ILC_FUL,  "ful",  "Fulah" },
    { mp4v2::impl::bmff::ILC_FUR,  "fur",  "Friulian" },
    { mp4v2::impl::bmff::ILC_GAA,  "gaa",  "Ga" },
    { mp4v2::impl::bmff::ILC_GAY,  "gay",  "Gayo" },
    { mp4v2::impl::bmff::ILC_GBA,  "gba",  "Gbaya" },
    { mp4v2::impl::bmff::ILC_GEM,  "gem",  "Germanic (Other)" },
    { mp4v2::impl::bmff::ILC_KAT,  "kat",  "Georgian" },
    { mp4v2::impl::bmff::ILC_DEU,  "deu",  "German" },
    { mp4v2::impl::bmff::ILC_GEZ,  "gez",  "Geez" },
    { mp4v2::impl::bmff::ILC_GIL,  "gil",  "Gilbertese" },
    { mp4v2::impl::bmff::ILC_GLA,  "gla",  "Gaelic; Scottish Gaelic" },
    { mp4v2::impl::bmff::ILC_GLE,  "gle",  "Irish" },
    { mp4v2::impl::bmff::ILC_GLG,  "glg",  "Galician" },
    { mp4v2::impl::bmff::ILC_GLV,  "glv",  "Manx" },
    { mp4v2::impl::bmff::ILC_GMH,  "gmh",  "German, Middle High (ca.1050-1500)" },
    { mp4v2::impl::bmff::ILC_GOH,  "goh",  "German, Old High (ca.750-1050)" },
    { mp4v2::impl::bmff::ILC_GON,  "gon",  "Gondi" },
    { mp4v2::impl::bmff::ILC_GOR,  "gor",  "Gorontalo" },
    { mp4v2::impl::bmff::ILC_GOT,  "got",  "Gothic" },
    { mp4v2::impl::bmff::ILC_GRB,  "grb",  "Grebo" },
    { mp4v2::impl::bmff::ILC_GRC,  "grc",  "Greek, Ancient (to 1453)" },
    { mp4v2::impl::bmff::ILC_ELL,  "ell",  "Greek, Modern (1453-)" },
    { mp4v2::impl::bmff::ILC_GRN,  "grn",  "Guarani" },
    { mp4v2::impl::bmff::ILC_GSW,  "gsw",  "Swiss German; Alemannic; Alsatian" },
    { mp4v2::impl::bmff::ILC_GUJ,  "guj",  "Gujarati" },
    { mp4v2::impl::bmff::ILC_GWI,  "gwi",  "Gwich'in" },
    { mp4v2::impl::bmff::ILC_HAI,  "hai",  "Haida" },
    { mp4v2::impl::bmff::ILC_HAT,  "hat",  "Haitian; Haitian Creole" },
    { mp4v2::impl::bmff::ILC_HAU,  "hau",  "Hausa" },
    { mp4v2::impl::bmff::ILC_HAW,  "haw",  "Hawaiian" },
    { mp4v2::impl::bmff::ILC_HEB,  "heb",  "Hebrew" },
    { mp4v2::impl::bmff::ILC_HER,  "her",  "Herero" },
    { mp4v2::impl::bmff::ILC_HIL,  "hil",  "Hiligaynon" },
    { mp4v2::impl::bmff::ILC_HIM,  "him",  "Himachali" },
    { mp4v2::impl::bmff::ILC_HIN,  "hin",  "Hindi" },
    { mp4v2::impl::bmff::ILC_HIT,  "hit",  "Hittite" },
    { mp4v2::impl::bmff::ILC_HMN,  "hmn",  "Hmong" },
    { mp4v2::impl::bmff::ILC_HMO,  "hmo",  "Hiri Motu" },
    { mp4v2::impl::bmff::ILC_HRV,  "hrv",  "Croatian" },
    { mp4v2::impl::bmff::ILC_HSB,  "hsb",  "Upper Sorbian" },
    { mp4v2::impl::bmff::ILC_HUN,  "hun",  "Hungarian" },
    { mp4v2::impl::bmff::ILC_HUP,  "hup",  "Hupa" },
    { mp4v2::impl::bmff::ILC_IBA,  "iba",  "Iban" },
    { mp4v2::impl::bmff::ILC_IBO,  "ibo",  "Igbo" },
    { mp4v2::impl::bmff::ILC_ISL,  "isl",  "Icelandic" },
    { mp4v2::impl::bmff::ILC_IDO,  "ido",  "Ido" },
    { mp4v2::impl::bmff::ILC_III,  "iii",  "Sichuan Yi; Nuosu" },
    { mp4v2::impl::bmff::ILC_IJO,  "ijo",  "Ijo languages" },
    { mp4v2::impl::bmff::ILC_IKU,  "iku",  "Inuktitut" },
    { mp4v2::impl::bmff::ILC_ILE,  "ile",  "Interlingue; Occidental" },
    { mp4v2::impl::bmff::ILC_ILO,  "ilo",  "Iloko" },
    { mp4v2::impl::bmff::ILC_INA,  "ina",  "Interlingua (International Auxiliary Language Association)" },
    { mp4v2::impl::bmff::ILC_INC,  "inc",  "Indic (Other)" },
    { mp4v2::impl::bmff::ILC_IND,  "ind",  "Indonesian" },
    { mp4v2::impl::bmff::ILC_INE,  "ine",  "Indo-European (Other)" },
    { mp4v2::impl::bmff::ILC_INH,  "inh",  "Ingush" },
    { mp4v2::impl::bmff::ILC_IPK,  "ipk",  "Inupiaq" },
    { mp4v2::impl::bmff::ILC_IRA,  "ira",  "Iranian (Other)" },
    { mp4v2::impl::bmff::ILC_IRO,  "iro",  "Iroquoian languages" },
    { mp4v2::impl::bmff::ILC_ITA,  "ita",  "Italian" },
    { mp4v2::impl::bmff::ILC_JAV,  "jav",  "Javanese" },
    { mp4v2::impl::bmff::ILC_JBO,  "jbo",  "Lojban" },
    { mp4v2::impl::bmff::ILC_JPN,  "jpn",  "Japanese" },
    { mp4v2::impl::bmff::ILC_JPR,  "jpr",  "Judeo-Persian" },
    { mp4v2::impl::bmff::ILC_JRB,  "jrb",  "Judeo-Arabic" },
    { mp4v2::impl::bmff::ILC_KAA,  "kaa",  "Kara-Kalpak" },
    { mp4v2::impl::bmff::ILC_KAB,  "kab",  "Kabyle" },
    { mp4v2::impl::bmff::ILC_KAC,  "kac",  "Kachin; Jingpho" },
    { mp4v2::impl::bmff::ILC_KAL,  "kal",  "Kalaallisut; Greenlandic" },
    { mp4v2::impl::bmff::ILC_KAM,  "kam",  "Kamba" },
    { mp4v2::impl::bmff::ILC_KAN,  "kan",  "Kannada" },
    { mp4v2::impl::bmff::ILC_KAR,  "kar",  "Karen languages" },
    { mp4v2::impl::bmff::ILC_KAS,  "kas",  "Kashmiri" },
    { mp4v2::impl::bmff::ILC_KAU,  "kau",  "Kanuri" },
    { mp4v2::impl::bmff::ILC_KAW,  "kaw",  "Kawi" },
    { mp4v2::impl::bmff::ILC_KAZ,  "kaz",  "Kazakh" },
    { mp4v2::impl::bmff::ILC_KBD,  "kbd",  "Kabardian" },
    { mp4v2::impl::bmff::ILC_KHA,  "kha",  "Khasi" },
    { mp4v2::impl::bmff::ILC_KHI,  "khi",  "Khoisan (Other)" },
    { mp4v2::impl::bmff::ILC_KHM,  "khm",  "Central Khmer" },
    { mp4v2::impl::bmff::ILC_KHO,  "kho",  "Khotanese; Sakan" },
    { mp4v2::impl::bmff::ILC_KIK,  "kik",  "Kikuyu; Gikuyu" },
    { mp4v2::impl::bmff::ILC_KIN,  "kin",  "Kinyarwanda" },
    { mp4v2::impl::bmff::ILC_KIR,  "kir",  "Kirghiz; Kyrgyz" },
    { mp4v2::impl::bmff::ILC_KMB,  "kmb",  "Kimbundu" },
    { mp4v2::impl::bmff::ILC_KOK,  "kok",  "Konkani" },
    { mp4v2::impl::bmff::ILC_KOM,  "kom",  "Komi" },
    { mp4v2::impl::bmff::ILC_KON,  "kon",  "Kongo" },
    { mp4v2::impl::bmff::ILC_KOR,  "kor",  "Korean" },
    { mp4v2::impl::bmff::ILC_KOS,  "kos",  "Kosraean" },
    { mp4v2::impl::bmff::ILC_KPE,  "kpe",  "Kpelle" },
    { mp4v2::impl::bmff::ILC_KRC,  "krc",  "Karachay-Balkar" },
    { mp4v2::impl::bmff::ILC_KRL,  "krl",  "Karelian" },
    { mp4v2::impl::bmff::ILC_KRO,  "kro",  "Kru languages" },
    { mp4v2::impl::bmff::ILC_KRU,  "kru",  "Kurukh" },
    { mp4v2::impl::bmff::ILC_KUA,  "kua",  "Kuanyama; Kwanyama" },
    { mp4v2::impl::bmff::ILC_KUM,  "kum",  "Kumyk" },
    { mp4v2::impl::bmff::ILC_KUR,  "kur",  "Kurdish" },
    { mp4v2::impl::bmff::ILC_KUT,  "kut",  "Kutenai" },
    { mp4v2::impl::bmff::ILC_LAD,  "lad",  "Ladino" },
    { mp4v2::impl::bmff::ILC_LAH,  "lah",  "Lahnda" },
    { mp4v2::impl::bmff::ILC_LAM,  "lam",  "Lamba" },
    { mp4v2::impl::bmff::ILC_LAO,  "lao",  "Lao" },
    { mp4v2::impl::bmff::ILC_LAT,  "lat",  "Latin" },
    { mp4v2::impl::bmff::ILC_LAV,  "lav",  "Latvian" },
    { mp4v2::impl::bmff::ILC_LEZ,  "lez",  "Lezghian" },
    { mp4v2::impl::bmff::ILC_LIM,  "lim",  "Limburgan; Limburger; Limburgish" },
    { mp4v2::impl::bmff::ILC_LIN,  "lin",  "Lingala" },
    { mp4v2::impl::bmff::ILC_LIT,  "lit",  "Lithuanian" },
    { mp4v2::impl::bmff::ILC_LOL,  "lol",  "Mongo" },
    { mp4v2::impl::bmff::ILC_LOZ,  "loz",  "Lozi" },
    { mp4v2::impl::bmff::ILC_LTZ,  "ltz",  "Luxembourgish; Letzeburgesch" },
    { mp4v2::impl::bmff::ILC_LUA,  "lua",  "Luba-Lulua" },
    { mp4v2::impl::bmff::ILC_LUB,  "lub",  "Luba-Katanga" },
    { mp4v2::impl::bmff::ILC_LUG,  "lug",  "Ganda" },
    { mp4v2::impl::bmff::ILC_LUI,  "lui",  "Luiseno" },
    { mp4v2::impl::bmff::ILC_LUN,  "lun",  "Lunda" },
    { mp4v2::impl::bmff::ILC_LUO,  "luo",  "Luo (Kenya and Tanzania)" },
    { mp4v2::impl::bmff::ILC_LUS,  "lus",  "Lushai" },
    { mp4v2::impl::bmff::ILC_MKD,  "mkd",  "Macedonian" },
    { mp4v2::impl::bmff::ILC_MAD,  "mad",  "Madurese" },
    { mp4v2::impl::bmff::ILC_MAG,  "mag",  "Magahi" },
    { mp4v2::impl::bmff::ILC_MAH,  "mah",  "Marshallese" },
    { mp4v2::impl::bmff::ILC_MAI,  "mai",  "Maithili" },
    { mp4v2::impl::bmff::ILC_MAK,  "mak",  "Makasar" },
    { mp4v2::impl::bmff::ILC_MAL,  "mal",  "Malayalam" },
    { mp4v2::impl::bmff::ILC_MAN,  "man",  "Mandingo" },
    { mp4v2::impl::bmff::ILC_MRI,  "mri",  "Maori" },
    { mp4v2::impl::bmff::ILC_MAP,  "map",  "Austronesian (Other)" },
    { mp4v2::impl::bmff::ILC_MAR,  "mar",  "Marathi" },
    { mp4v2::impl::bmff::ILC_MAS,  "mas",  "Masai" },
    { mp4v2::impl::bmff::ILC_MSA,  "msa",  "Malay" },
    { mp4v2::impl::bmff::ILC_MDF,  "mdf",  "Moksha" },
    { mp4v2::impl::bmff::ILC_MDR,  "mdr",  "Mandar" },
    { mp4v2::impl::bmff::ILC_MEN,  "men",  "Mende" },
    { mp4v2::impl::bmff::ILC_MGA,  "mga",  "Irish, Middle (900-1200)" },
    { mp4v2::impl::bmff::ILC_MIC,  "mic",  "Mi'kmaq; Micmac" },
    { mp4v2::impl::bmff::ILC_MIN,  "min",  "Minangkabau" },
    { mp4v2::impl::bmff::ILC_MIS,  "mis",  "Uncoded languages" },
    { mp4v2::impl::bmff::ILC_MKH,  "mkh",  "Mon-Khmer (Other)" },
    { mp4v2::impl::bmff::ILC_MLG,  "mlg",  "Malagasy" },
    { mp4v2::impl::bmff::ILC_MLT,  "mlt",  "Maltese" },
    { mp4v2::impl::bmff::ILC_MNC,  "mnc",  "Manchu" },
    { mp4v2::impl::bmff::ILC_MNI,  "mni",  "Manipuri" },
    { mp4v2::impl::bmff::ILC_MNO,  "mno",  "Manobo languages" },
    { mp4v2::impl::bmff::ILC_MOH,  "moh",  "Mohawk" },
    { mp4v2::impl::bmff::ILC_MON,  "mon",  "Mongolian" },
    { mp4v2::impl::bmff::ILC_MOS,  "mos",  "Mossi" },
    { mp4v2::impl::bmff::ILC_MUL,  "mul",  "Multiple languages" },
    { mp4v2::impl::bmff::ILC_MUN,  "mun",  "Munda languages" },
    { mp4v2::impl::bmff::ILC_MUS,  "mus",  "Creek" },
    { mp4v2::impl::bmff::ILC_MWL,  "mwl",  "Mirandese" },
    { mp4v2::impl::bmff::ILC_MWR,  "mwr",  "Marwari" },
    { mp4v2::impl::bmff::ILC_MYN,  "myn",  "Mayan languages" },
    { mp4v2::impl::bmff::ILC_MYV,  "myv",  "Erzya" },
    { mp4v2::impl::bmff::ILC_NAH,  "nah",  "Nahuatl languages" },
    { mp4v2::impl::bmff::ILC_NAI,  "nai",  "North American Indian" },
    { mp4v2::impl::bmff::ILC_NAP,  "nap",  "Neapolitan" },
    { mp4v2::impl::bmff::ILC_NAU,  "nau",  "Nauru" },
    { mp4v2::impl::bmff::ILC_NAV,  "nav",  "Navajo; Navaho" },
    { mp4v2::impl::bmff::ILC_NBL,  "nbl",  "Ndebele, South; South Ndebele" },
    { mp4v2::impl::bmff::ILC_NDE,  "nde",  "Ndebele, North; North Ndebele" },
    { mp4v2::impl::bmff::ILC_NDO,  "ndo",  "Ndonga" },
    { mp4v2::impl::bmff::ILC_NDS,  "nds",  "Low German; Low Saxon; German, Low; Saxon, Low" },
    { mp4v2::impl::bmff::ILC_NEP,  "nep",  "Nepali" },
    { mp4v2::impl::bmff::ILC_NEW,  "new",  "Nepal Bhasa; Newari" },
    { mp4v2::impl::bmff::ILC_NIA,  "nia",  "Nias" },
    { mp4v2::impl::bmff::ILC_NIC,  "nic",  "Niger-Kordofanian (Other)" },
    { mp4v2::impl::bmff::ILC_NIU,  "niu",  "Niuean" },
    { mp4v2::impl::bmff::ILC_NNO,  "nno",  "Norwegian Nynorsk; Nynorsk, Norwegian" },
    { mp4v2::impl::bmff::ILC_NOB,  "nob",  "Bokmål, Norwegian; Norwegian Bokmål" },
    { mp4v2::impl::bmff::ILC_NOG,  "nog",  "Nogai" },
    { mp4v2::impl::bmff::ILC_NON,  "non",  "Norse, Old" },
    { mp4v2::impl::bmff::ILC_NOR,  "nor",  "Norwegian" },
    { mp4v2::impl::bmff::ILC_NQO,  "nqo",  "N'Ko" },
    { mp4v2::impl::bmff::ILC_NSO,  "nso",  "Pedi; Sepedi; Northern Sotho" },
    { mp4v2::impl::bmff::ILC_NUB,  "nub",  "Nubian languages" },
    { mp4v2::impl::bmff::ILC_NWC,  "nwc",  "Classical Newari; Old Newari; Classical Nepal Bhasa" },
    { mp4v2::impl::bmff::ILC_NYA,  "nya",  "Chichewa; Chewa; Nyanja" },
    { mp4v2::impl::bmff::ILC_NYM,  "nym",  "Nyamwezi" },
    { mp4v2::impl::bmff::ILC_NYN,  "nyn",  "Nyankole" },
    { mp4v2::impl::bmff::ILC_NYO,  "nyo",  "Nyoro" },
    { mp4v2::impl::bmff::ILC_NZI,  "nzi",  "Nzima" },
    { mp4v2::impl::bmff::ILC_OCI,  "oci",  "Occitan (post 1500); Provençal" },
    { mp4v2::impl::bmff::ILC_OJI,  "oji",  "Ojibwa" },
    { mp4v2::impl::bmff::ILC_ORI,  "ori",  "Oriya" },
    { mp4v2::impl::bmff::ILC_ORM,  "orm",  "Oromo" },
    { mp4v2::impl::bmff::ILC_OSA,  "osa",  "Osage" },
    { mp4v2::impl::bmff::ILC_OSS,  "oss",  "Ossetian; Ossetic" },
    { mp4v2::impl::bmff::ILC_OTA,  "ota",  "Turkish, Ottoman (1500-1928)" },
    { mp4v2::impl::bmff::ILC_OTO,  "oto",  "Otomian languages" },
    { mp4v2::impl::bmff::ILC_PAA,  "paa",  "Papuan (Other)" },
    { mp4v2::impl::bmff::ILC_PAG,  "pag",  "Pangasinan" },
    { mp4v2::impl::bmff::ILC_PAL,  "pal",  "Pahlavi" },
    { mp4v2::impl::bmff::ILC_PAM,  "pam",  "Pampanga; Kapampangan" },
    { mp4v2::impl::bmff::ILC_PAN,  "pan",  "Panjabi; Punjabi" },
    { mp4v2::impl::bmff::ILC_PAP,  "pap",  "Papiamento" },
    { mp4v2::impl::bmff::ILC_PAU,  "pau",  "Palauan" },
    { mp4v2::impl::bmff::ILC_PEO,  "peo",  "Persian, Old (ca.600-400 B.C.)" },
    { mp4v2::impl::bmff::ILC_FAS,  "fas",  "Persian" },
    { mp4v2::impl::bmff::ILC_PHI,  "phi",  "Philippine (Other)" },
    { mp4v2::impl::bmff::ILC_PHN,  "phn",  "Phoenician" },
    { mp4v2::impl::bmff::ILC_PLI,  "pli",  "Pali" },
    { mp4v2::impl::bmff::ILC_POL,  "pol",  "Polish" },
    { mp4v2::impl::bmff::ILC_PON,  "pon",  "Pohnpeian" },
    { mp4v2::impl::bmff::ILC_POR,  "por",  "Portuguese" },
    { mp4v2::impl::bmff::ILC_PRA,  "pra",  "Prakrit languages" },
    { mp4v2::impl::bmff::ILC_PRO,  "pro",  "Provençal, Old (to 1500)" },
    { mp4v2::impl::bmff::ILC_PUS,  "pus",  "Pushto; Pashto" },
    { mp4v2::impl::bmff::ILC_QAA,  "qaa",  "Reserved for local use (qaa)" },
    { mp4v2::impl::bmff::ILC_QAB,  "qab",  "Reserved for local use (qab)" },
    { mp4v2::impl::bmff::ILC_QAC,  "qac",  "Reserved for local use (qac)" },
    { mp4v2::impl::bmff::ILC_QAD,  "qad",  "Reserved for local use (qad)" },
    { mp4v2::impl::bmff::ILC_QAE,  "qae",  "Reserved for local use (qae)" },
    { mp4v2::impl::bmff::ILC_QAF,  "qaf",  "Reserved for local use (qaf)" },
    { mp4v2::impl::bmff::ILC_QAG,  "qag",  "Reserved for local use (qag)" },
    { mp4v2::impl::bmff::ILC_QAH,  "qah",  "Reserved for local use (qah)" },
    { mp4v2::impl::bmff::ILC_QAI,  "qai",  "Reserved for local use (qai)" },
    { mp4v2::impl::bmff::ILC_QAJ,  "qaj",  "Reserved for local use (qaj)" },
    { mp4v2::impl::bmff::ILC_QAK,  "qak",  "Reserved for local use (qak)" },
    { mp4v2::impl::bmff::ILC_QAL,  "qal",  "Reserved for local use (qal)" },
    { mp4v2::impl::bmff::ILC_QAM,  "qam",  "Reserved for local use (qam)" },
    { mp4v2::impl::bmff::ILC_QAN,  "qan",  "Reserved for local use (qan)" },
    { mp4v2::impl::bmff::ILC_QAO,  "qao",  "Reserved for local use (qao)" },
    { mp4v2::impl::bmff::ILC_QAP,  "qap",  "Reserved for local use (qap)" },
    { mp4v2::impl::bmff::ILC_QAQ,  "qaq",  "Reserved for local use (qaq)" },
    { mp4v2::impl::bmff::ILC_QAR,  "qar",  "Reserved for local use (qar)" },
    { mp4v2::impl::bmff::ILC_QAS,  "qas",  "Reserved for local use (qas)" },
    { mp4v2::impl::bmff::ILC_QAT,  "qat",  "Reserved for local use (qat)" },
    { mp4v2::impl::bmff::ILC_QAU,  "qau",  "Reserved for local use (qau)" },
    { mp4v2::impl::bmff::ILC_QAV,  "qav",  "Reserved for local use (qav)" },
    { mp4v2::impl::bmff::ILC_QAW,  "qaw",  "Reserved for local use (qaw)" },
    { mp4v2::impl::bmff::ILC_QAX,  "qax",  "Reserved for local use (qax)" },
    { mp4v2::impl::bmff::ILC_QAY,  "qay",  "Reserved for local use (qay)" },
    { mp4v2::impl::bmff::ILC_QAZ,  "qaz",  "Reserved for local use (qaz)" },
    { mp4v2::impl::bmff::ILC_QBA,  "qba",  "Reserved for local use (qba)" },
    { mp4v2::impl::bmff::ILC_QBB,  "qbb",  "Reserved for local use (qbb)" },
    { mp4v2::impl::bmff::ILC_QBC,  "qbc",  "Reserved for local use (qbc)" },
    { mp4v2::impl::bmff::ILC_QBD,  "qbd",  "Reserved for local use (qbd)" },
    { mp4v2::impl::bmff::ILC_QBE,  "qbe",  "Reserved for local use (qbe)" },
    { mp4v2::impl::bmff::ILC_QBF,  "qbf",  "Reserved for local use (qbf)" },
    { mp4v2::impl::bmff::ILC_QBG,  "qbg",  "Reserved for local use (qbg)" },
    { mp4v2::impl::bmff::ILC_QBH,  "qbh",  "Reserved for local use (qbh)" },
    { mp4v2::impl::bmff::ILC_QBI,  "qbi",  "Reserved for local use (qbi)" },
    { mp4v2::impl::bmff::ILC_QBJ,  "qbj",  "Reserved for local use (qbj)" },
    { mp4v2::impl::bmff::ILC_QBK,  "qbk",  "Reserved for local use (qbk)" },
    { mp4v2::impl::bmff::ILC_QBL,  "qbl",  "Reserved for local use (qbl)" },
    { mp4v2::impl::bmff::ILC_QBM,  "qbm",  "Reserved for local use (qbm)" },
    { mp4v2::impl::bmff::ILC_QBN,  "qbn",  "Reserved for local use (qbn)" },
    { mp4v2::impl::bmff::ILC_QBO,  "qbo",  "Reserved for local use (qbo)" },
    { mp4v2::impl::bmff::ILC_QBP,  "qbp",  "Reserved for local use (qbp)" },
    { mp4v2::impl::bmff::ILC_QBQ,  "qbq",  "Reserved for local use (qbq)" },
    { mp4v2::impl::bmff::ILC_QBR,  "qbr",  "Reserved for local use (qbr)" },
    { mp4v2::impl::bmff::ILC_QBS,  "qbs",  "Reserved for local use (qbs)" },
    { mp4v2::impl::bmff::ILC_QBT,  "qbt",  "Reserved for local use (qbt)" },
    { mp4v2::impl::bmff::ILC_QBU,  "qbu",  "Reserved for local use (qbu)" },
    { mp4v2::impl::bmff::ILC_QBV,  "qbv",  "Reserved for local use (qbv)" },
    { mp4v2::impl::bmff::ILC_QBW,  "qbw",  "Reserved for local use (qbw)" },
    { mp4v2::impl::bmff::ILC_QBX,  "qbx",  "Reserved for local use (qbx)" },
    { mp4v2::impl::bmff::ILC_QBY,  "qby",  "Reserved for local use (qby)" },
    { mp4v2::impl::bmff::ILC_QBZ,  "qbz",  "Reserved for local use (qbz)" },
    { mp4v2::impl::bmff::ILC_QCA,  "qca",  "Reserved for local use (qca)" },
    { mp4v2::impl::bmff::ILC_QCB,  "qcb",  "Reserved for local use (qcb)" },
    { mp4v2::impl::bmff::ILC_QCC,  "qcc",  "Reserved for local use (qcc)" },
    { mp4v2::impl::bmff::ILC_QCD,  "qcd",  "Reserved for local use (qcd)" },
    { mp4v2::impl::bmff::ILC_QCE,  "qce",  "Reserved for local use (qce)" },
    { mp4v2::impl::bmff::ILC_QCF,  "qcf",  "Reserved for local use (qcf)" },
    { mp4v2::impl::bmff::ILC_QCG,  "qcg",  "Reserved for local use (qcg)" },
    { mp4v2::impl::bmff::ILC_QCH,  "qch",  "Reserved for local use (qch)" },
    { mp4v2::impl::bmff::ILC_QCI,  "qci",  "Reserved for local use (qci)" },
    { mp4v2::impl::bmff::ILC_QCJ,  "qcj",  "Reserved for local use (qcj)" },
    { mp4v2::impl::bmff::ILC_QCK,  "qck",  "Reserved for local use (qck)" },
    { mp4v2::impl::bmff::ILC_QCL,  "qcl",  "Reserved for local use (qcl)" },
    { mp4v2::impl::bmff::ILC_QCM,  "qcm",  "Reserved for local use (qcm)" },
    { mp4v2::impl::bmff::ILC_QCN,  "qcn",  "Reserved for local use (qcn)" },
    { mp4v2::impl::bmff::ILC_QCO,  "qco",  "Reserved for local use (qco)" },
    { mp4v2::impl::bmff::ILC_QCP,  "qcp",  "Reserved for local use (qcp)" },
    { mp4v2::impl::bmff::ILC_QCQ,  "qcq",  "Reserved for local use (qcq)" },
    { mp4v2::impl::bmff::ILC_QCR,  "qcr",  "Reserved for local use (qcr)" },
    { mp4v2::impl::bmff::ILC_QCS,  "qcs",  "Reserved for local use (qcs)" },
    { mp4v2::impl::bmff::ILC_QCT,  "qct",  "Reserved for local use (qct)" },
    { mp4v2::impl::bmff::ILC_QCU,  "qcu",  "Reserved for local use (qcu)" },
    { mp4v2::impl::bmff::ILC_QCV,  "qcv",  "Reserved for local use (qcv)" },
    { mp4v2::impl::bmff::ILC_QCW,  "qcw",  "Reserved for local use (qcw)" },
    { mp4v2::impl::bmff::ILC_QCX,  "qcx",  "Reserved for local use (qcx)" },
    { mp4v2::impl::bmff::ILC_QCY,  "qcy",  "Reserved for local use (qcy)" },
    { mp4v2::impl::bmff::ILC_QCZ,  "qcz",  "Reserved for local use (qcz)" },
    { mp4v2::impl::bmff::ILC_QDA,  "qda",  "Reserved for local use (qda)" },
    { mp4v2::impl::bmff::ILC_QDB,  "qdb",  "Reserved for local use (qdb)" },
    { mp4v2::impl::bmff::ILC_QDC,  "qdc",  "Reserved for local use (qdc)" },
    { mp4v2::impl::bmff::ILC_QDD,  "qdd",  "Reserved for local use (qdd)" },
    { mp4v2::impl::bmff::ILC_QDE,  "qde",  "Reserved for local use (qde)" },
    { mp4v2::impl::bmff::ILC_QDF,  "qdf",  "Reserved for local use (qdf)" },
    { mp4v2::impl::bmff::ILC_QDG,  "qdg",  "Reserved for local use (qdg)" },
    { mp4v2::impl::bmff::ILC_QDH,  "qdh",  "Reserved for local use (qdh)" },
    { mp4v2::impl::bmff::ILC_QDI,  "qdi",  "Reserved for local use (qdi)" },
    { mp4v2::impl::bmff::ILC_QDJ,  "qdj",  "Reserved for local use (qdj)" },
    { mp4v2::impl::bmff::ILC_QDK,  "qdk",  "Reserved for local use (qdk)" },
    { mp4v2::impl::bmff::ILC_QDL,  "qdl",  "Reserved for local use (qdl)" },
    { mp4v2::impl::bmff::ILC_QDM,  "qdm",  "Reserved for local use (qdm)" },
    { mp4v2::impl::bmff::ILC_QDN,  "qdn",  "Reserved for local use (qdn)" },
    { mp4v2::impl::bmff::ILC_QDO,  "qdo",  "Reserved for local use (qdo)" },
    { mp4v2::impl::bmff::ILC_QDP,  "qdp",  "Reserved for local use (qdp)" },
    { mp4v2::impl::bmff::ILC_QDQ,  "qdq",  "Reserved for local use (qdq)" },
    { mp4v2::impl::bmff::ILC_QDR,  "qdr",  "Reserved for local use (qdr)" },
    { mp4v2::impl::bmff::ILC_QDS,  "qds",  "Reserved for local use (qds)" },
    { mp4v2::impl::bmff::ILC_QDT,  "qdt",  "Reserved for local use (qdt)" },
    { mp4v2::impl::bmff::ILC_QDU,  "qdu",  "Reserved for local use (qdu)" },
    { mp4v2::impl::bmff::ILC_QDV,  "qdv",  "Reserved for local use (qdv)" },
    { mp4v2::impl::bmff::ILC_QDW,  "qdw",  "Reserved for local use (qdw)" },
    { mp4v2::impl::bmff::ILC_QDX,  "qdx",  "Reserved for local use (qdx)" },
    { mp4v2::impl::bmff::ILC_QDY,  "qdy",  "Reserved for local use (qdy)" },
    { mp4v2::impl::bmff::ILC_QDZ,  "qdz",  "Reserved for local use (qdz)" },
    { mp4v2::impl::bmff::ILC_QEA,  "qea",  "Reserved for local use (qea)" },
    { mp4v2::impl::bmff::ILC_QEB,  "qeb",  "Reserved for local use (qeb)" },
    { mp4v2::impl::bmff::ILC_QEC,  "qec",  "Reserved for local use (qec)" },
    { mp4v2::impl::bmff::ILC_QED,  "qed",  "Reserved for local use (qed)" },
    { mp4v2::impl::bmff::ILC_QEE,  "qee",  "Reserved for local use (qee)" },
    { mp4v2::impl::bmff::ILC_QEF,  "qef",  "Reserved for local use (qef)" },
    { mp4v2::impl::bmff::ILC_QEG,  "qeg",  "Reserved for local use (qeg)" },
    { mp4v2::impl::bmff::ILC_QEH,  "qeh",  "Reserved for local use (qeh)" },
    { mp4v2::impl::bmff::ILC_QEI,  "qei",  "Reserved for local use (qei)" },
    { mp4v2::impl::bmff::ILC_QEJ,  "qej",  "Reserved for local use (qej)" },
    { mp4v2::impl::bmff::ILC_QEK,  "qek",  "Reserved for local use (qek)" },
    { mp4v2::impl::bmff::ILC_QEL,  "qel",  "Reserved for local use (qel)" },
    { mp4v2::impl::bmff::ILC_QEM,  "qem",  "Reserved for local use (qem)" },
    { mp4v2::impl::bmff::ILC_QEN,  "qen",  "Reserved for local use (qen)" },
    { mp4v2::impl::bmff::ILC_QEO,  "qeo",  "Reserved for local use (qeo)" },
    { mp4v2::impl::bmff::ILC_QEP,  "qep",  "Reserved for local use (qep)" },
    { mp4v2::impl::bmff::ILC_QEQ,  "qeq",  "Reserved for local use (qeq)" },
    { mp4v2::impl::bmff::ILC_QER,  "qer",  "Reserved for local use (qer)" },
    { mp4v2::impl::bmff::ILC_QES,  "qes",  "Reserved for local use (qes)" },
    { mp4v2::impl::bmff::ILC_QET,  "qet",  "Reserved for local use (qet)" },
    { mp4v2::impl::bmff::ILC_QEU,  "qeu",  "Reserved for local use (qeu)" },
    { mp4v2::impl::bmff::ILC_QEV,  "qev",  "Reserved for local use (qev)" },
    { mp4v2::impl::bmff::ILC_QEW,  "qew",  "Reserved for local use (qew)" },
    { mp4v2::impl::bmff::ILC_QEX,  "qex",  "Reserved for local use (qex)" },
    { mp4v2::impl::bmff::ILC_QEY,  "qey",  "Reserved for local use (qey)" },
    { mp4v2::impl::bmff::ILC_QEZ,  "qez",  "Reserved for local use (qez)" },
    { mp4v2::impl::bmff::ILC_QFA,  "qfa",  "Reserved for local use (qfa)" },
    { mp4v2::impl::bmff::ILC_QFB,  "qfb",  "Reserved for local use (qfb)" },
    { mp4v2::impl::bmff::ILC_QFC,  "qfc",  "Reserved for local use (qfc)" },
    { mp4v2::impl::bmff::ILC_QFD,  "qfd",  "Reserved for local use (qfd)" },
    { mp4v2::impl::bmff::ILC_QFE,  "qfe",  "Reserved for local use (qfe)" },
    { mp4v2::impl::bmff::ILC_QFF,  "qff",  "Reserved for local use (qff)" },
    { mp4v2::impl::bmff::ILC_QFG,  "qfg",  "Reserved for local use (qfg)" },
    { mp4v2::impl::bmff::ILC_QFH,  "qfh",  "Reserved for local use (qfh)" },
    { mp4v2::impl::bmff::ILC_QFI,  "qfi",  "Reserved for local use (qfi)" },
    { mp4v2::impl::bmff::ILC_QFJ,  "qfj",  "Reserved for local use (qfj)" },
    { mp4v2::impl::bmff::ILC_QFK,  "qfk",  "Reserved for local use (qfk)" },
    { mp4v2::impl::bmff::ILC_QFL,  "qfl",  "Reserved for local use (qfl)" },
    { mp4v2::impl::bmff::ILC_QFM,  "qfm",  "Reserved for local use (qfm)" },
    { mp4v2::impl::bmff::ILC_QFN,  "qfn",  "Reserved for local use (qfn)" },
    { mp4v2::impl::bmff::ILC_QFO,  "qfo",  "Reserved for local use (qfo)" },
    { mp4v2::impl::bmff::ILC_QFP,  "qfp",  "Reserved for local use (qfp)" },
    { mp4v2::impl::bmff::ILC_QFQ,  "qfq",  "Reserved for local use (qfq)" },
    { mp4v2::impl::bmff::ILC_QFR,  "qfr",  "Reserved for local use (qfr)" },
    { mp4v2::impl::bmff::ILC_QFS,  "qfs",  "Reserved for local use (qfs)" },
    { mp4v2::impl::bmff::ILC_QFT,  "qft",  "Reserved for local use (qft)" },
    { mp4v2::impl::bmff::ILC_QFU,  "qfu",  "Reserved for local use (qfu)" },
    { mp4v2::impl::bmff::ILC_QFV,  "qfv",  "Reserved for local use (qfv)" },
    { mp4v2::impl::bmff::ILC_QFW,  "qfw",  "Reserved for local use (qfw)" },
    { mp4v2::impl::bmff::ILC_QFX,  "qfx",  "Reserved for local use (qfx)" },
    { mp4v2::impl::bmff::ILC_QFY,  "qfy",  "Reserved for local use (qfy)" },
    { mp4v2::impl::bmff::ILC_QFZ,  "qfz",  "Reserved for local use (qfz)" },
    { mp4v2::impl::bmff::ILC_QGA,  "qga",  "Reserved for local use (qga)" },
    { mp4v2::impl::bmff::ILC_QGB,  "qgb",  "Reserved for local use (qgb)" },
    { mp4v2::impl::bmff::ILC_QGC,  "qgc",  "Reserved for local use (qgc)" },
    { mp4v2::impl::bmff::ILC_QGD,  "qgd",  "Reserved for local use (qgd)" },
    { mp4v2::impl::bmff::ILC_QGE,  "qge",  "Reserved for local use (qge)" },
    { mp4v2::impl::bmff::ILC_QGF,  "qgf",  "Reserved for local use (qgf)" },
    { mp4v2::impl::bmff::ILC_QGG,  "qgg",  "Reserved for local use (qgg)" },
    { mp4v2::impl::bmff::ILC_QGH,  "qgh",  "Reserved for local use (qgh)" },
    { mp4v2::impl::bmff::ILC_QGI,  "qgi",  "Reserved for local use (qgi)" },
    { mp4v2::impl::bmff::ILC_QGJ,  "qgj",  "Reserved for local use (qgj)" },
    { mp4v2::impl::bmff::ILC_QGK,  "qgk",  "Reserved for local use (qgk)" },
    { mp4v2::impl::bmff::ILC_QGL,  "qgl",  "Reserved for local use (qgl)" },
    { mp4v2::impl::bmff::ILC_QGM,  "qgm",  "Reserved for local use (qgm)" },
    { mp4v2::impl::bmff::ILC_QGN,  "qgn",  "Reserved for local use (qgn)" },
    { mp4v2::impl::bmff::ILC_QGO,  "qgo",  "Reserved for local use (qgo)" },
    { mp4v2::impl::bmff::ILC_QGP,  "qgp",  "Reserved for local use (qgp)" },
    { mp4v2::impl::bmff::ILC_QGQ,  "qgq",  "Reserved for local use (qgq)" },
    { mp4v2::impl::bmff::ILC_QGR,  "qgr",  "Reserved for local use (qgr)" },
    { mp4v2::impl::bmff::ILC_QGS,  "qgs",  "Reserved for local use (qgs)" },
    { mp4v2::impl::bmff::ILC_QGT,  "qgt",  "Reserved for local use (qgt)" },
    { mp4v2::impl::bmff::ILC_QGU,  "qgu",  "Reserved for local use (qgu)" },
    { mp4v2::impl::bmff::ILC_QGV,  "qgv",  "Reserved for local use (qgv)" },
    { mp4v2::impl::bmff::ILC_QGW,  "qgw",  "Reserved for local use (qgw)" },
    { mp4v2::impl::bmff::ILC_QGX,  "qgx",  "Reserved for local use (qgx)" },
    { mp4v2::impl::bmff::ILC_QGY,  "qgy",  "Reserved for local use (qgy)" },
    { mp4v2::impl::bmff::ILC_QGZ,  "qgz",  "Reserved for local use (qgz)" },
    { mp4v2::impl::bmff::ILC_QHA,  "qha",  "Reserved for local use (qha)" },
    { mp4v2::impl::bmff::ILC_QHB,  "qhb",  "Reserved for local use (qhb)" },
    { mp4v2::impl::bmff::ILC_QHC,  "qhc",  "Reserved for local use (qhc)" },
    { mp4v2::impl::bmff::ILC_QHD,  "qhd",  "Reserved for local use (qhd)" },
    { mp4v2::impl::bmff::ILC_QHE,  "qhe",  "Reserved for local use (qhe)" },
    { mp4v2::impl::bmff::ILC_QHF,  "qhf",  "Reserved for local use (qhf)" },
    { mp4v2::impl::bmff::ILC_QHG,  "qhg",  "Reserved for local use (qhg)" },
    { mp4v2::impl::bmff::ILC_QHH,  "qhh",  "Reserved for local use (qhh)" },
    { mp4v2::impl::bmff::ILC_QHI,  "qhi",  "Reserved for local use (qhi)" },
    { mp4v2::impl::bmff::ILC_QHJ,  "qhj",  "Reserved for local use (qhj)" },
    { mp4v2::impl::bmff::ILC_QHK,  "qhk",  "Reserved for local use (qhk)" },
    { mp4v2::impl::bmff::ILC_QHL,  "qhl",  "Reserved for local use (qhl)" },
    { mp4v2::impl::bmff::ILC_QHM,  "qhm",  "Reserved for local use (qhm)" },
    { mp4v2::impl::bmff::ILC_QHN,  "qhn",  "Reserved for local use (qhn)" },
    { mp4v2::impl::bmff::ILC_QHO,  "qho",  "Reserved for local use (qho)" },
    { mp4v2::impl::bmff::ILC_QHP,  "qhp",  "Reserved for local use (qhp)" },
    { mp4v2::impl::bmff::ILC_QHQ,  "qhq",  "Reserved for local use (qhq)" },
    { mp4v2::impl::bmff::ILC_QHR,  "qhr",  "Reserved for local use (qhr)" },
    { mp4v2::impl::bmff::ILC_QHS,  "qhs",  "Reserved for local use (qhs)" },
    { mp4v2::impl::bmff::ILC_QHT,  "qht",  "Reserved for local use (qht)" },
    { mp4v2::impl::bmff::ILC_QHU,  "qhu",  "Reserved for local use (qhu)" },
    { mp4v2::impl::bmff::ILC_QHV,  "qhv",  "Reserved for local use (qhv)" },
    { mp4v2::impl::bmff::ILC_QHW,  "qhw",  "Reserved for local use (qhw)" },
    { mp4v2::impl::bmff::ILC_QHX,  "qhx",  "Reserved for local use (qhx)" },
    { mp4v2::impl::bmff::ILC_QHY,  "qhy",  "Reserved for local use (qhy)" },
    { mp4v2::impl::bmff::ILC_QHZ,  "qhz",  "Reserved for local use (qhz)" },
    { mp4v2::impl::bmff::ILC_QIA,  "qia",  "Reserved for local use (qia)" },
    { mp4v2::impl::bmff::ILC_QIB,  "qib",  "Reserved for local use (qib)" },
    { mp4v2::impl::bmff::ILC_QIC,  "qic",  "Reserved for local use (qic)" },
    { mp4v2::impl::bmff::ILC_QID,  "qid",  "Reserved for local use (qid)" },
    { mp4v2::impl::bmff::ILC_QIE,  "qie",  "Reserved for local use (qie)" },
    { mp4v2::impl::bmff::ILC_QIF,  "qif",  "Reserved for local use (qif)" },
    { mp4v2::impl::bmff::ILC_QIG,  "qig",  "Reserved for local use (qig)" },
    { mp4v2::impl::bmff::ILC_QIH,  "qih",  "Reserved for local use (qih)" },
    { mp4v2::impl::bmff::ILC_QII,  "qii",  "Reserved for local use (qii)" },
    { mp4v2::impl::bmff::ILC_QIJ,  "qij",  "Reserved for local use (qij)" },
    { mp4v2::impl::bmff::ILC_QIK,  "qik",  "Reserved for local use (qik)" },
    { mp4v2::impl::bmff::ILC_QIL,  "qil",  "Reserved for local use (qil)" },
    { mp4v2::impl::bmff::ILC_QIM,  "qim",  "Reserved for local use (qim)" },
    { mp4v2::impl::bmff::ILC_QIN,  "qin",  "Reserved for local use (qin)" },
    { mp4v2::impl::bmff::ILC_QIO,  "qio",  "Reserved for local use (qio)" },
    { mp4v2::impl::bmff::ILC_QIP,  "qip",  "Reserved for local use (qip)" },
    { mp4v2::impl::bmff::ILC_QIQ,  "qiq",  "Reserved for local use (qiq)" },
    { mp4v2::impl::bmff::ILC_QIR,  "qir",  "Reserved for local use (qir)" },
    { mp4v2::impl::bmff::ILC_QIS,  "qis",  "Reserved for local use (qis)" },
    { mp4v2::impl::bmff::ILC_QIT,  "qit",  "Reserved for local use (qit)" },
    { mp4v2::impl::bmff::ILC_QIU,  "qiu",  "Reserved for local use (qiu)" },
    { mp4v2::impl::bmff::ILC_QIV,  "qiv",  "Reserved for local use (qiv)" },
    { mp4v2::impl::bmff::ILC_QIW,  "qiw",  "Reserved for local use (qiw)" },
    { mp4v2::impl::bmff::ILC_QIX,  "qix",  "Reserved for local use (qix)" },
    { mp4v2::impl::bmff::ILC_QIY,  "qiy",  "Reserved for local use (qiy)" },
    { mp4v2::impl::bmff::ILC_QIZ,  "qiz",  "Reserved for local use (qiz)" },
    { mp4v2::impl::bmff::ILC_QJA,  "qja",  "Reserved for local use (qja)" },
    { mp4v2::impl::bmff::ILC_QJB,  "qjb",  "Reserved for local use (qjb)" },
    { mp4v2::impl::bmff::ILC_QJC,  "qjc",  "Reserved for local use (qjc)" },
    { mp4v2::impl::bmff::ILC_QJD,  "qjd",  "Reserved for local use (qjd)" },
    { mp4v2::impl::bmff::ILC_QJE,  "qje",  "Reserved for local use (qje)" },
    { mp4v2::impl::bmff::ILC_QJF,  "qjf",  "Reserved for local use (qjf)" },
    { mp4v2::impl::bmff::ILC_QJG,  "qjg",  "Reserved for local use (qjg)" },
    { mp4v2::impl::bmff::ILC_QJH,  "qjh",  "Reserved for local use (qjh)" },
    { mp4v2::impl::bmff::ILC_QJI,  "qji",  "Reserved for local use (qji)" },
    { mp4v2::impl::bmff::ILC_QJJ,  "qjj",  "Reserved for local use (qjj)" },
    { mp4v2::impl::bmff::ILC_QJK,  "qjk",  "Reserved for local use (qjk)" },
    { mp4v2::impl::bmff::ILC_QJL,  "qjl",  "Reserved for local use (qjl)" },
    { mp4v2::impl::bmff::ILC_QJM,  "qjm",  "Reserved for local use (qjm)" },
    { mp4v2::impl::bmff::ILC_QJN,  "qjn",  "Reserved for local use (qjn)" },
    { mp4v2::impl::bmff::ILC_QJO,  "qjo",  "Reserved for local use (qjo)" },
    { mp4v2::impl::bmff::ILC_QJP,  "qjp",  "Reserved for local use (qjp)" },
    { mp4v2::impl::bmff::ILC_QJQ,  "qjq",  "Reserved for local use (qjq)" },
    { mp4v2::impl::bmff::ILC_QJR,  "qjr",  "Reserved for local use (qjr)" },
    { mp4v2::impl::bmff::ILC_QJS,  "qjs",  "Reserved for local use (qjs)" },
    { mp4v2::impl::bmff::ILC_QJT,  "qjt",  "Reserved for local use (qjt)" },
    { mp4v2::impl::bmff::ILC_QJU,  "qju",  "Reserved for local use (qju)" },
    { mp4v2::impl::bmff::ILC_QJV,  "qjv",  "Reserved for local use (qjv)" },
    { mp4v2::impl::bmff::ILC_QJW,  "qjw",  "Reserved for local use (qjw)" },
    { mp4v2::impl::bmff::ILC_QJX,  "qjx",  "Reserved for local use (qjx)" },
    { mp4v2::impl::bmff::ILC_QJY,  "qjy",  "Reserved for local use (qjy)" },
    { mp4v2::impl::bmff::ILC_QJZ,  "qjz",  "Reserved for local use (qjz)" },
    { mp4v2::impl::bmff::ILC_QKA,  "qka",  "Reserved for local use (qka)" },
    { mp4v2::impl::bmff::ILC_QKB,  "qkb",  "Reserved for local use (qkb)" },
    { mp4v2::impl::bmff::ILC_QKC,  "qkc",  "Reserved for local use (qkc)" },
    { mp4v2::impl::bmff::ILC_QKD,  "qkd",  "Reserved for local use (qkd)" },
    { mp4v2::impl::bmff::ILC_QKE,  "qke",  "Reserved for local use (qke)" },
    { mp4v2::impl::bmff::ILC_QKF,  "qkf",  "Reserved for local use (qkf)" },
    { mp4v2::impl::bmff::ILC_QKG,  "qkg",  "Reserved for local use (qkg)" },
    { mp4v2::impl::bmff::ILC_QKH,  "qkh",  "Reserved for local use (qkh)" },
    { mp4v2::impl::bmff::ILC_QKI,  "qki",  "Reserved for local use (qki)" },
    { mp4v2::impl::bmff::ILC_QKJ,  "qkj",  "Reserved for local use (qkj)" },
    { mp4v2::impl::bmff::ILC_QKK,  "qkk",  "Reserved for local use (qkk)" },
    { mp4v2::impl::bmff::ILC_QKL,  "qkl",  "Reserved for local use (qkl)" },
    { mp4v2::impl::bmff::ILC_QKM,  "qkm",  "Reserved for local use (qkm)" },
    { mp4v2::impl::bmff::ILC_QKN,  "qkn",  "Reserved for local use (qkn)" },
    { mp4v2::impl::bmff::ILC_QKO,  "qko",  "Reserved for local use (qko)" },
    { mp4v2::impl::bmff::ILC_QKP,  "qkp",  "Reserved for local use (qkp)" },
    { mp4v2::impl::bmff::ILC_QKQ,  "qkq",  "Reserved for local use (qkq)" },
    { mp4v2::impl::bmff::ILC_QKR,  "qkr",  "Reserved for local use (qkr)" },
    { mp4v2::impl::bmff::ILC_QKS,  "qks",  "Reserved for local use (qks)" },
    { mp4v2::impl::bmff::ILC_QKT,  "qkt",  "Reserved for local use (qkt)" },
    { mp4v2::impl::bmff::ILC_QKU,  "qku",  "Reserved for local use (qku)" },
    { mp4v2::impl::bmff::ILC_QKV,  "qkv",  "Reserved for local use (qkv)" },
    { mp4v2::impl::bmff::ILC_QKW,  "qkw",  "Reserved for local use (qkw)" },
    { mp4v2::impl::bmff::ILC_QKX,  "qkx",  "Reserved for local use (qkx)" },
    { mp4v2::impl::bmff::ILC_QKY,  "qky",  "Reserved for local use (qky)" },
    { mp4v2::impl::bmff::ILC_QKZ,  "qkz",  "Reserved for local use (qkz)" },
    { mp4v2::impl::bmff::ILC_QLA,  "qla",  "Reserved for local use (qla)" },
    { mp4v2::impl::bmff::ILC_QLB,  "qlb",  "Reserved for local use (qlb)" },
    { mp4v2::impl::bmff::ILC_QLC,  "qlc",  "Reserved for local use (qlc)" },
    { mp4v2::impl::bmff::ILC_QLD,  "qld",  "Reserved for local use (qld)" },
    { mp4v2::impl::bmff::ILC_QLE,  "qle",  "Reserved for local use (qle)" },
    { mp4v2::impl::bmff::ILC_QLF,  "qlf",  "Reserved for local use (qlf)" },
    { mp4v2::impl::bmff::ILC_QLG,  "qlg",  "Reserved for local use (qlg)" },
    { mp4v2::impl::bmff::ILC_QLH,  "qlh",  "Reserved for local use (qlh)" },
    { mp4v2::impl::bmff::ILC_QLI,  "qli",  "Reserved for local use (qli)" },
    { mp4v2::impl::bmff::ILC_QLJ,  "qlj",  "Reserved for local use (qlj)" },
    { mp4v2::impl::bmff::ILC_QLK,  "qlk",  "Reserved for local use (qlk)" },
    { mp4v2::impl::bmff::ILC_QLL,  "qll",  "Reserved for local use (qll)" },
    { mp4v2::impl::bmff::ILC_QLM,  "qlm",  "Reserved for local use (qlm)" },
    { mp4v2::impl::bmff::ILC_QLN,  "qln",  "Reserved for local use (qln)" },
    { mp4v2::impl::bmff::ILC_QLO,  "qlo",  "Reserved for local use (qlo)" },
    { mp4v2::impl::bmff::ILC_QLP,  "qlp",  "Reserved for local use (qlp)" },
    { mp4v2::impl::bmff::ILC_QLQ,  "qlq",  "Reserved for local use (qlq)" },
    { mp4v2::impl::bmff::ILC_QLR,  "qlr",  "Reserved for local use (qlr)" },
    { mp4v2::impl::bmff::ILC_QLS,  "qls",  "Reserved for local use (qls)" },
    { mp4v2::impl::bmff::ILC_QLT,  "qlt",  "Reserved for local use (qlt)" },
    { mp4v2::impl::bmff::ILC_QLU,  "qlu",  "Reserved for local use (qlu)" },
    { mp4v2::impl::bmff::ILC_QLV,  "qlv",  "Reserved for local use (qlv)" },
    { mp4v2::impl::bmff::ILC_QLW,  "qlw",  "Reserved for local use (qlw)" },
    { mp4v2::impl::bmff::ILC_QLX,  "qlx",  "Reserved for local use (qlx)" },
    { mp4v2::impl::bmff::ILC_QLY,  "qly",  "Reserved for local use (qly)" },
    { mp4v2::impl::bmff::ILC_QLZ,  "qlz",  "Reserved for local use (qlz)" },
    { mp4v2::impl::bmff::ILC_QMA,  "qma",  "Reserved for local use (qma)" },
    { mp4v2::impl::bmff::ILC_QMB,  "qmb",  "Reserved for local use (qmb)" },
    { mp4v2::impl::bmff::ILC_QMC,  "qmc",  "Reserved for local use (qmc)" },
    { mp4v2::impl::bmff::ILC_QMD,  "qmd",  "Reserved for local use (qmd)" },
    { mp4v2::impl::bmff::ILC_QME,  "qme",  "Reserved for local use (qme)" },
    { mp4v2::impl::bmff::ILC_QMF,  "qmf",  "Reserved for local use (qmf)" },
    { mp4v2::impl::bmff::ILC_QMG,  "qmg",  "Reserved for local use (qmg)" },
    { mp4v2::impl::bmff::ILC_QMH,  "qmh",  "Reserved for local use (qmh)" },
    { mp4v2::impl::bmff::ILC_QMI,  "qmi",  "Reserved for local use (qmi)" },
    { mp4v2::impl::bmff::ILC_QMJ,  "qmj",  "Reserved for local use (qmj)" },
    { mp4v2::impl::bmff::ILC_QMK,  "qmk",  "Reserved for local use (qmk)" },
    { mp4v2::impl::bmff::ILC_QML,  "qml",  "Reserved for local use (qml)" },
    { mp4v2::impl::bmff::ILC_QMM,  "qmm",  "Reserved for local use (qmm)" },
    { mp4v2::impl::bmff::ILC_QMN,  "qmn",  "Reserved for local use (qmn)" },
    { mp4v2::impl::bmff::ILC_QMO,  "qmo",  "Reserved for local use (qmo)" },
    { mp4v2::impl::bmff::ILC_QMP,  "qmp",  "Reserved for local use (qmp)" },
    { mp4v2::impl::bmff::ILC_QMQ,  "qmq",  "Reserved for local use (qmq)" },
    { mp4v2::impl::bmff::ILC_QMR,  "qmr",  "Reserved for local use (qmr)" },
    { mp4v2::impl::bmff::ILC_QMS,  "qms",  "Reserved for local use (qms)" },
    { mp4v2::impl::bmff::ILC_QMT,  "qmt",  "Reserved for local use (qmt)" },
    { mp4v2::impl::bmff::ILC_QMU,  "qmu",  "Reserved for local use (qmu)" },
    { mp4v2::impl::bmff::ILC_QMV,  "qmv",  "Reserved for local use (qmv)" },
    { mp4v2::impl::bmff::ILC_QMW,  "qmw",  "Reserved for local use (qmw)" },
    { mp4v2::impl::bmff::ILC_QMX,  "qmx",  "Reserved for local use (qmx)" },
    { mp4v2::impl::bmff::ILC_QMY,  "qmy",  "Reserved for local use (qmy)" },
    { mp4v2::impl::bmff::ILC_QMZ,  "qmz",  "Reserved for local use (qmz)" },
    { mp4v2::impl::bmff::ILC_QNA,  "qna",  "Reserved for local use (qna)" },
    { mp4v2::impl::bmff::ILC_QNB,  "qnb",  "Reserved for local use (qnb)" },
    { mp4v2::impl::bmff::ILC_QNC,  "qnc",  "Reserved for local use (qnc)" },
    { mp4v2::impl::bmff::ILC_QND,  "qnd",  "Reserved for local use (qnd)" },
    { mp4v2::impl::bmff::ILC_QNE,  "qne",  "Reserved for local use (qne)" },
    { mp4v2::impl::bmff::ILC_QNF,  "qnf",  "Reserved for local use (qnf)" },
    { mp4v2::impl::bmff::ILC_QNG,  "qng",  "Reserved for local use (qng)" },
    { mp4v2::impl::bmff::ILC_QNH,  "qnh",  "Reserved for local use (qnh)" },
    { mp4v2::impl::bmff::ILC_QNI,  "qni",  "Reserved for local use (qni)" },
    { mp4v2::impl::bmff::ILC_QNJ,  "qnj",  "Reserved for local use (qnj)" },
    { mp4v2::impl::bmff::ILC_QNK,  "qnk",  "Reserved for local use (qnk)" },
    { mp4v2::impl::bmff::ILC_QNL,  "qnl",  "Reserved for local use (qnl)" },
    { mp4v2::impl::bmff::ILC_QNM,  "qnm",  "Reserved for local use (qnm)" },
    { mp4v2::impl::bmff::ILC_QNN,  "qnn",  "Reserved for local use (qnn)" },
    { mp4v2::impl::bmff::ILC_QNO,  "qno",  "Reserved for local use (qno)" },
    { mp4v2::impl::bmff::ILC_QNP,  "qnp",  "Reserved for local use (qnp)" },
    { mp4v2::impl::bmff::ILC_QNQ,  "qnq",  "Reserved for local use (qnq)" },
    { mp4v2::impl::bmff::ILC_QNR,  "qnr",  "Reserved for local use (qnr)" },
    { mp4v2::impl::bmff::ILC_QNS,  "qns",  "Reserved for local use (qns)" },
    { mp4v2::impl::bmff::ILC_QNT,  "qnt",  "Reserved for local use (qnt)" },
    { mp4v2::impl::bmff::ILC_QNU,  "qnu",  "Reserved for local use (qnu)" },
    { mp4v2::impl::bmff::ILC_QNV,  "qnv",  "Reserved for local use (qnv)" },
    { mp4v2::impl::bmff::ILC_QNW,  "qnw",  "Reserved for local use (qnw)" },
    { mp4v2::impl::bmff::ILC_QNX,  "qnx",  "Reserved for local use (qnx)" },
    { mp4v2::impl::bmff::ILC_QNY,  "qny",  "Reserved for local use (qny)" },
    { mp4v2::impl::bmff::ILC_QNZ,  "qnz",  "Reserved for local use (qnz)" },
    { mp4v2::impl::bmff::ILC_QOA,  "qoa",  "Reserved for local use (qoa)" },
    { mp4v2::impl::bmff::ILC_QOB,  "qob",  "Reserved for local use (qob)" },
    { mp4v2::impl::bmff::ILC_QOC,  "qoc",  "Reserved for local use (qoc)" },
    { mp4v2::impl::bmff::ILC_QOD,  "qod",  "Reserved for local use (qod)" },
    { mp4v2::impl::bmff::ILC_QOE,  "qoe",  "Reserved for local use (qoe)" },
    { mp4v2::impl::bmff::ILC_QOF,  "qof",  "Reserved for local use (qof)" },
    { mp4v2::impl::bmff::ILC_QOG,  "qog",  "Reserved for local use (qog)" },
    { mp4v2::impl::bmff::ILC_QOH,  "qoh",  "Reserved for local use (qoh)" },
    { mp4v2::impl::bmff::ILC_QOI,  "qoi",  "Reserved for local use (qoi)" },
    { mp4v2::impl::bmff::ILC_QOJ,  "qoj",  "Reserved for local use (qoj)" },
    { mp4v2::impl::bmff::ILC_QOK,  "qok",  "Reserved for local use (qok)" },
    { mp4v2::impl::bmff::ILC_QOL,  "qol",  "Reserved for local use (qol)" },
    { mp4v2::impl::bmff::ILC_QOM,  "qom",  "Reserved for local use (qom)" },
    { mp4v2::impl::bmff::ILC_QON,  "qon",  "Reserved for local use (qon)" },
    { mp4v2::impl::bmff::ILC_QOO,  "qoo",  "Reserved for local use (qoo)" },
    { mp4v2::impl::bmff::ILC_QOP,  "qop",  "Reserved for local use (qop)" },
    { mp4v2::impl::bmff::ILC_QOQ,  "qoq",  "Reserved for local use (qoq)" },
    { mp4v2::impl::bmff::ILC_QOR,  "qor",  "Reserved for local use (qor)" },
    { mp4v2::impl::bmff::ILC_QOS,  "qos",  "Reserved for local use (qos)" },
    { mp4v2::impl::bmff::ILC_QOT,  "qot",  "Reserved for local use (qot)" },
    { mp4v2::impl::bmff::ILC_QOU,  "qou",  "Reserved for local use (qou)" },
    { mp4v2::impl::bmff::ILC_QOV,  "qov",  "Reserved for local use (qov)" },
    { mp4v2::impl::bmff::ILC_QOW,  "qow",  "Reserved for local use (qow)" },
    { mp4v2::impl::bmff::ILC_QOX,  "qox",  "Reserved for local use (qox)" },
    { mp4v2::impl::bmff::ILC_QOY,  "qoy",  "Reserved for local use (qoy)" },
    { mp4v2::impl::bmff::ILC_QOZ,  "qoz",  "Reserved for local use (qoz)" },
    { mp4v2::impl::bmff::ILC_QPA,  "qpa",  "Reserved for local use (qpa)" },
    { mp4v2::impl::bmff::ILC_QPB,  "qpb",  "Reserved for local use (qpb)" },
    { mp4v2::impl::bmff::ILC_QPC,  "qpc",  "Reserved for local use (qpc)" },
    { mp4v2::impl::bmff::ILC_QPD,  "qpd",  "Reserved for local use (qpd)" },
    { mp4v2::impl::bmff::ILC_QPE,  "qpe",  "Reserved for local use (qpe)" },
    { mp4v2::impl::bmff::ILC_QPF,  "qpf",  "Reserved for local use (qpf)" },
    { mp4v2::impl::bmff::ILC_QPG,  "qpg",  "Reserved for local use (qpg)" },
    { mp4v2::impl::bmff::ILC_QPH,  "qph",  "Reserved for local use (qph)" },
    { mp4v2::impl::bmff::ILC_QPI,  "qpi",  "Reserved for local use (qpi)" },
    { mp4v2::impl::bmff::ILC_QPJ,  "qpj",  "Reserved for local use (qpj)" },
    { mp4v2::impl::bmff::ILC_QPK,  "qpk",  "Reserved for local use (qpk)" },
    { mp4v2::impl::bmff::ILC_QPL,  "qpl",  "Reserved for local use (qpl)" },
    { mp4v2::impl::bmff::ILC_QPM,  "qpm",  "Reserved for local use (qpm)" },
    { mp4v2::impl::bmff::ILC_QPN,  "qpn",  "Reserved for local use (qpn)" },
    { mp4v2::impl::bmff::ILC_QPO,  "qpo",  "Reserved for local use (qpo)" },
    { mp4v2::impl::bmff::ILC_QPP,  "qpp",  "Reserved for local use (qpp)" },
    { mp4v2::impl::bmff::ILC_QPQ,  "qpq",  "Reserved for local use (qpq)" },
    { mp4v2::impl::bmff::ILC_QPR,  "qpr",  "Reserved for local use (qpr)" },
    { mp4v2::impl::bmff::ILC_QPS,  "qps",  "Reserved for local use (qps)" },
    { mp4v2::impl::bmff::ILC_QPT,  "qpt",  "Reserved for local use (qpt)" },
    { mp4v2::impl::bmff::ILC_QPU,  "qpu",  "Reserved for local use (qpu)" },
    { mp4v2::impl::bmff::ILC_QPV,  "qpv",  "Reserved for local use (qpv)" },
    { mp4v2::impl::bmff::ILC_QPW,  "qpw",  "Reserved for local use (qpw)" },
    { mp4v2::impl::bmff::ILC_QPX,  "qpx",  "Reserved for local use (qpx)" },
    { mp4v2::impl::bmff::ILC_QPY,  "qpy",  "Reserved for local use (qpy)" },
    { mp4v2::impl::bmff::ILC_QPZ,  "qpz",  "Reserved for local use (qpz)" },
    { mp4v2::impl::bmff::ILC_QQA,  "qqa",  "Reserved for local use (qqa)" },
    { mp4v2::impl::bmff::ILC_QQB,  "qqb",  "Reserved for local use (qqb)" },
    { mp4v2::impl::bmff::ILC_QQC,  "qqc",  "Reserved for local use (qqc)" },
    { mp4v2::impl::bmff::ILC_QQD,  "qqd",  "Reserved for local use (qqd)" },
    { mp4v2::impl::bmff::ILC_QQE,  "qqe",  "Reserved for local use (qqe)" },
    { mp4v2::impl::bmff::ILC_QQF,  "qqf",  "Reserved for local use (qqf)" },
    { mp4v2::impl::bmff::ILC_QQG,  "qqg",  "Reserved for local use (qqg)" },
    { mp4v2::impl::bmff::ILC_QQH,  "qqh",  "Reserved for local use (qqh)" },
    { mp4v2::impl::bmff::ILC_QQI,  "qqi",  "Reserved for local use (qqi)" },
    { mp4v2::impl::bmff::ILC_QQJ,  "qqj",  "Reserved for local use (qqj)" },
    { mp4v2::impl::bmff::ILC_QQK,  "qqk",  "Reserved for local use (qqk)" },
    { mp4v2::impl::bmff::ILC_QQL,  "qql",  "Reserved for local use (qql)" },
    { mp4v2::impl::bmff::ILC_QQM,  "qqm",  "Reserved for local use (qqm)" },
    { mp4v2::impl::bmff::ILC_QQN,  "qqn",  "Reserved for local use (qqn)" },
    { mp4v2::impl::bmff::ILC_QQO,  "qqo",  "Reserved for local use (qqo)" },
    { mp4v2::impl::bmff::ILC_QQP,  "qqp",  "Reserved for local use (qqp)" },
    { mp4v2::impl::bmff::ILC_QQQ,  "qqq",  "Reserved for local use (qqq)" },
    { mp4v2::impl::bmff::ILC_QQR,  "qqr",  "Reserved for local use (qqr)" },
    { mp4v2::impl::bmff::ILC_QQS,  "qqs",  "Reserved for local use (qqs)" },
    { mp4v2::impl::bmff::ILC_QQT,  "qqt",  "Reserved for local use (qqt)" },
    { mp4v2::impl::bmff::ILC_QQU,  "qqu",  "Reserved for local use (qqu)" },
    { mp4v2::impl::bmff::ILC_QQV,  "qqv",  "Reserved for local use (qqv)" },
    { mp4v2::impl::bmff::ILC_QQW,  "qqw",  "Reserved for local use (qqw)" },
    { mp4v2::impl::bmff::ILC_QQX,  "qqx",  "Reserved for local use (qqx)" },
    { mp4v2::impl::bmff::ILC_QQY,  "qqy",  "Reserved for local use (qqy)" },
    { mp4v2::impl::bmff::ILC_QQZ,  "qqz",  "Reserved for local use (qqz)" },
    { mp4v2::impl::bmff::ILC_QRA,  "qra",  "Reserved for local use (qra)" },
    { mp4v2::impl::bmff::ILC_QRB,  "qrb",  "Reserved for local use (qrb)" },
    { mp4v2::impl::bmff::ILC_QRC,  "qrc",  "Reserved for local use (qrc)" },
    { mp4v2::impl::bmff::ILC_QRD,  "qrd",  "Reserved for local use (qrd)" },
    { mp4v2::impl::bmff::ILC_QRE,  "qre",  "Reserved for local use (qre)" },
    { mp4v2::impl::bmff::ILC_QRF,  "qrf",  "Reserved for local use (qrf)" },
    { mp4v2::impl::bmff::ILC_QRG,  "qrg",  "Reserved for local use (qrg)" },
    { mp4v2::impl::bmff::ILC_QRH,  "qrh",  "Reserved for local use (qrh)" },
    { mp4v2::impl::bmff::ILC_QRI,  "qri",  "Reserved for local use (qri)" },
    { mp4v2::impl::bmff::ILC_QRJ,  "qrj",  "Reserved for local use (qrj)" },
    { mp4v2::impl::bmff::ILC_QRK,  "qrk",  "Reserved for local use (qrk)" },
    { mp4v2::impl::bmff::ILC_QRL,  "qrl",  "Reserved for local use (qrl)" },
    { mp4v2::impl::bmff::ILC_QRM,  "qrm",  "Reserved for local use (qrm)" },
    { mp4v2::impl::bmff::ILC_QRN,  "qrn",  "Reserved for local use (qrn)" },
    { mp4v2::impl::bmff::ILC_QRO,  "qro",  "Reserved for local use (qro)" },
    { mp4v2::impl::bmff::ILC_QRP,  "qrp",  "Reserved for local use (qrp)" },
    { mp4v2::impl::bmff::ILC_QRQ,  "qrq",  "Reserved for local use (qrq)" },
    { mp4v2::impl::bmff::ILC_QRR,  "qrr",  "Reserved for local use (qrr)" },
    { mp4v2::impl::bmff::ILC_QRS,  "qrs",  "Reserved for local use (qrs)" },
    { mp4v2::impl::bmff::ILC_QRT,  "qrt",  "Reserved for local use (qrt)" },
    { mp4v2::impl::bmff::ILC_QRU,  "qru",  "Reserved for local use (qru)" },
    { mp4v2::impl::bmff::ILC_QRV,  "qrv",  "Reserved for local use (qrv)" },
    { mp4v2::impl::bmff::ILC_QRW,  "qrw",  "Reserved for local use (qrw)" },
    { mp4v2::impl::bmff::ILC_QRX,  "qrx",  "Reserved for local use (qrx)" },
    { mp4v2::impl::bmff::ILC_QRY,  "qry",  "Reserved for local use (qry)" },
    { mp4v2::impl::bmff::ILC_QRZ,  "qrz",  "Reserved for local use (qrz)" },
    { mp4v2::impl::bmff::ILC_QSA,  "qsa",  "Reserved for local use (qsa)" },
    { mp4v2::impl::bmff::ILC_QSB,  "qsb",  "Reserved for local use (qsb)" },
    { mp4v2::impl::bmff::ILC_QSC,  "qsc",  "Reserved for local use (qsc)" },
    { mp4v2::impl::bmff::ILC_QSD,  "qsd",  "Reserved for local use (qsd)" },
    { mp4v2::impl::bmff::ILC_QSE,  "qse",  "Reserved for local use (qse)" },
    { mp4v2::impl::bmff::ILC_QSF,  "qsf",  "Reserved for local use (qsf)" },
    { mp4v2::impl::bmff::ILC_QSG,  "qsg",  "Reserved for local use (qsg)" },
    { mp4v2::impl::bmff::ILC_QSH,  "qsh",  "Reserved for local use (qsh)" },
    { mp4v2::impl::bmff::ILC_QSI,  "qsi",  "Reserved for local use (qsi)" },
    { mp4v2::impl::bmff::ILC_QSJ,  "qsj",  "Reserved for local use (qsj)" },
    { mp4v2::impl::bmff::ILC_QSK,  "qsk",  "Reserved for local use (qsk)" },
    { mp4v2::impl::bmff::ILC_QSL,  "qsl",  "Reserved for local use (qsl)" },
    { mp4v2::impl::bmff::ILC_QSM,  "qsm",  "Reserved for local use (qsm)" },
    { mp4v2::impl::bmff::ILC_QSN,  "qsn",  "Reserved for local use (qsn)" },
    { mp4v2::impl::bmff::ILC_QSO,  "qso",  "Reserved for local use (qso)" },
    { mp4v2::impl::bmff::ILC_QSP,  "qsp",  "Reserved for local use (qsp)" },
    { mp4v2::impl::bmff::ILC_QSQ,  "qsq",  "Reserved for local use (qsq)" },
    { mp4v2::impl::bmff::ILC_QSR,  "qsr",  "Reserved for local use (qsr)" },
    { mp4v2::impl::bmff::ILC_QSS,  "qss",  "Reserved for local use (qss)" },
    { mp4v2::impl::bmff::ILC_QST,  "qst",  "Reserved for local use (qst)" },
    { mp4v2::impl::bmff::ILC_QSU,  "qsu",  "Reserved for local use (qsu)" },
    { mp4v2::impl::bmff::ILC_QSV,  "qsv",  "Reserved for local use (qsv)" },
    { mp4v2::impl::bmff::ILC_QSW,  "qsw",  "Reserved for local use (qsw)" },
    { mp4v2::impl::bmff::ILC_QSX,  "qsx",  "Reserved for local use (qsx)" },
    { mp4v2::impl::bmff::ILC_QSY,  "qsy",  "Reserved for local use (qsy)" },
    { mp4v2::impl::bmff::ILC_QSZ,  "qsz",  "Reserved for local use (qsz)" },
    { mp4v2::impl::bmff::ILC_QTA,  "qta",  "Reserved for local use (qta)" },
    { mp4v2::impl::bmff::ILC_QTB,  "qtb",  "Reserved for local use (qtb)" },
    { mp4v2::impl::bmff::ILC_QTC,  "qtc",  "Reserved for local use (qtc)" },
    { mp4v2::impl::bmff::ILC_QTD,  "qtd",  "Reserved for local use (qtd)" },
    { mp4v2::impl::bmff::ILC_QTE,  "qte",  "Reserved for local use (qte)" },
    { mp4v2::impl::bmff::ILC_QTF,  "qtf",  "Reserved for local use (qtf)" },
    { mp4v2::impl::bmff::ILC_QTG,  "qtg",  "Reserved for local use (qtg)" },
    { mp4v2::impl::bmff::ILC_QTH,  "qth",  "Reserved for local use (qth)" },
    { mp4v2::impl::bmff::ILC_QTI,  "qti",  "Reserved for local use (qti)" },
    { mp4v2::impl::bmff::ILC_QTJ,  "qtj",  "Reserved for local use (qtj)" },
    { mp4v2::impl::bmff::ILC_QTK,  "qtk",  "Reserved for local use (qtk)" },
    { mp4v2::impl::bmff::ILC_QTL,  "qtl",  "Reserved for local use (qtl)" },
    { mp4v2::impl::bmff::ILC_QTM,  "qtm",  "Reserved for local use (qtm)" },
    { mp4v2::impl::bmff::ILC_QTN,  "qtn",  "Reserved for local use (qtn)" },
    { mp4v2::impl::bmff::ILC_QTO,  "qto",  "Reserved for local use (qto)" },
    { mp4v2::impl::bmff::ILC_QTP,  "qtp",  "Reserved for local use (qtp)" },
    { mp4v2::impl::bmff::ILC_QTQ,  "qtq",  "Reserved for local use (qtq)" },
    { mp4v2::impl::bmff::ILC_QTR,  "qtr",  "Reserved for local use (qtr)" },
    { mp4v2::impl::bmff::ILC_QTS,  "qts",  "Reserved for local use (qts)" },
    { mp4v2::impl::bmff::ILC_QTT,  "qtt",  "Reserved for local use (qtt)" },
    { mp4v2::impl::bmff::ILC_QTU,  "qtu",  "Reserved for local use (qtu)" },
    { mp4v2::impl::bmff::ILC_QTV,  "qtv",  "Reserved for local use (qtv)" },
    { mp4v2::impl::bmff::ILC_QTW,  "qtw",  "Reserved for local use (qtw)" },
    { mp4v2::impl::bmff::ILC_QTX,  "qtx",  "Reserved for local use (qtx)" },
    { mp4v2::impl::bmff::ILC_QTY,  "qty",  "Reserved for local use (qty)" },
    { mp4v2::impl::bmff::ILC_QTZ,  "qtz",  "Reserved for local use (qtz)" },
    { mp4v2::impl::bmff::ILC_QUE,  "que",  "Quechua" },
    { mp4v2::impl::bmff::ILC_RAJ,  "raj",  "Rajasthani" },
    { mp4v2::impl::bmff::ILC_RAP,  "rap",  "Rapanui" },
    { mp4v2::impl::bmff::ILC_RAR,  "rar",  "Rarotongan; Cook Islands Maori" },
    { mp4v2::impl::bmff::ILC_ROA,  "roa",  "Romance (Other)" },
    { mp4v2::impl::bmff::ILC_ROH,  "roh",  "Romansh" },
    { mp4v2::impl::bmff::ILC_ROM,  "rom",  "Romany" },
    { mp4v2::impl::bmff::ILC_RON,  "ron",  "Romanian; Moldavian; Moldovan" },
    { mp4v2::impl::bmff::ILC_RUN,  "run",  "Rundi" },
    { mp4v2::impl::bmff::ILC_RUP,  "rup",  "Aromanian; Arumanian; Macedo-Romanian" },
    { mp4v2::impl::bmff::ILC_RUS,  "rus",  "Russian" },
    { mp4v2::impl::bmff::ILC_SAD,  "sad",  "Sandawe" },
    { mp4v2::impl::bmff::ILC_SAG,  "sag",  "Sango" },
    { mp4v2::impl::bmff::ILC_SAH,  "sah",  "Yakut" },
    { mp4v2::impl::bmff::ILC_SAI,  "sai",  "South American Indian (Other)" },
    { mp4v2::impl::bmff::ILC_SAL,  "sal",  "Salishan languages" },
    { mp4v2::impl::bmff::ILC_SAM,  "sam",  "Samaritan Aramaic" },
    { mp4v2::impl::bmff::ILC_SAN,  "san",  "Sanskrit" },
    { mp4v2::impl::bmff::ILC_SAS,  "sas",  "Sasak" },
    { mp4v2::impl::bmff::ILC_SAT,  "sat",  "Santali" },
    { mp4v2::impl::bmff::ILC_SCN,  "scn",  "Sicilian" },
    { mp4v2::impl::bmff::ILC_SCO,  "sco",  "Scots" },
    { mp4v2::impl::bmff::ILC_SEL,  "sel",  "Selkup" },
    { mp4v2::impl::bmff::ILC_SEM,  "sem",  "Semitic (Other)" },
    { mp4v2::impl::bmff::ILC_SGA,  "sga",  "Irish, Old (to 900)" },
    { mp4v2::impl::bmff::ILC_SGN,  "sgn",  "Sign Languages" },
    { mp4v2::impl::bmff::ILC_SHN,  "shn",  "Shan" },
    { mp4v2::impl::bmff::ILC_SID,  "sid",  "Sidamo" },
    { mp4v2::impl::bmff::ILC_SIN,  "sin",  "Sinhala; Sinhalese" },
    { mp4v2::impl::bmff::ILC_SIO,  "sio",  "Siouan languages" },
    { mp4v2::impl::bmff::ILC_SIT,  "sit",  "Sino-Tibetan (Other)" },
    { mp4v2::impl::bmff::ILC_SLA,  "sla",  "Slavic (Other)" },
    { mp4v2::impl::bmff::ILC_SLK,  "slk",  "Slovak" },
    { mp4v2::impl::bmff::ILC_SLV,  "slv",  "Slovenian" },
    { mp4v2::impl::bmff::ILC_SMA,  "sma",  "Southern Sami" },
    { mp4v2::impl::bmff::ILC_SME,  "sme",  "Northern Sami" },
    { mp4v2::impl::bmff::ILC_SMI,  "smi",  "Sami languages (Other)" },
    { mp4v2::impl::bmff::ILC_SMJ,  "smj",  "Lule Sami" },
    { mp4v2::impl::bmff::ILC_SMN,  "smn",  "Inari Sami" },
    { mp4v2::impl::bmff::ILC_SMO,  "smo",  "Samoan" },
    { mp4v2::impl::bmff::ILC_SMS,  "sms",  "Skolt Sami" },
    { mp4v2::impl::bmff::ILC_SNA,  "sna",  "Shona" },
    { mp4v2::impl::bmff::ILC_SND,  "snd",  "Sindhi" },
    { mp4v2::impl::bmff::ILC_SNK,  "snk",  "Soninke" },
    { mp4v2::impl::bmff::ILC_SOG,  "sog",  "Sogdian" },
    { mp4v2::impl::bmff::ILC_SOM,  "som",  "Somali" },
    { mp4v2::impl::bmff::ILC_SON,  "son",  "Songhai languages" },
    { mp4v2::impl::bmff::ILC_SOT,  "sot",  "Sotho, Southern" },
    { mp4v2::impl::bmff::ILC_SPA,  "spa",  "Spanish; Castilian" },
    { mp4v2::impl::bmff::ILC_SRD,  "srd",  "Sardinian" },
    { mp4v2::impl::bmff::ILC_SRN,  "srn",  "Sranan Tongo" },
    { mp4v2::impl::bmff::ILC_SRP,  "srp",  "Serbian" },
    { mp4v2::impl::bmff::ILC_SRR,  "srr",  "Serer" },
    { mp4v2::impl::bmff::ILC_SSA,  "ssa",  "Nilo-Saharan (Other)" },
    { mp4v2::impl::bmff::ILC_SSW,  "ssw",  "Swati" },
    { mp4v2::impl::bmff::ILC_SUK,  "suk",  "Sukuma" },
    { mp4v2::impl::bmff::ILC_SUN,  "sun",  "Sundanese" },
    { mp4v2::impl::bmff::ILC_SUS,  "sus",  "Susu" },
    { mp4v2::impl::bmff::ILC_SUX,  "sux",  "Sumerian" },
    { mp4v2::impl::bmff::ILC_SWA,  "swa",  "Swahili" },
    { mp4v2::impl::bmff::ILC_SWE,  "swe",  "Swedish" },
    { mp4v2::impl::bmff::ILC_SYC,  "syc",  "Classical Syriac" },
    { mp4v2::impl::bmff::ILC_SYR,  "syr",  "Syriac" },
    { mp4v2::impl::bmff::ILC_TAH,  "tah",  "Tahitian" },
    { mp4v2::impl::bmff::ILC_TAI,  "tai",  "Tai (Other)" },
    { mp4v2::impl::bmff::ILC_TAM,  "tam",  "Tamil" },
    { mp4v2::impl::bmff::ILC_TAT,  "tat",  "Tatar" },
    { mp4v2::impl::bmff::ILC_TEL,  "tel",  "Telugu" },
    { mp4v2::impl::bmff::ILC_TEM,  "tem",  "Timne" },
    { mp4v2::impl::bmff::ILC_TER,  "ter",  "Tereno" },
    { mp4v2::impl::bmff::ILC_TET,  "tet",  "Tetum" },
    { mp4v2::impl::bmff::ILC_TGK,  "tgk",  "Tajik" },
    { mp4v2::impl::bmff::ILC_TGL,  "tgl",  "Tagalog" },
    { mp4v2::impl::bmff::ILC_THA,  "tha",  "Thai" },
    { mp4v2::impl::bmff::ILC_BOD,  "bod",  "Tibetan" },
    { mp4v2::impl::bmff::ILC_TIG,  "tig",  "Tigre" },
    { mp4v2::impl::bmff::ILC_TIR,  "tir",  "Tigrinya" },
    { mp4v2::impl::bmff::ILC_TIV,  "tiv",  "Tiv" },
    { mp4v2::impl::bmff::ILC_TKL,  "tkl",  "Tokelau" },
    { mp4v2::impl::bmff::ILC_TLH,  "tlh",  "Klingon; tlhIngan-Hol" },
    { mp4v2::impl::bmff::ILC_TLI,  "tli",  "Tlingit" },
    { mp4v2::impl::bmff::ILC_TMH,  "tmh",  "Tamashek" },
    { mp4v2::impl::bmff::ILC_TOG,  "tog",  "Tonga (Nyasa)" },
    { mp4v2::impl::bmff::ILC_TON,  "ton",  "Tonga (Tonga Islands)" },
    { mp4v2::impl::bmff::ILC_TPI,  "tpi",  "Tok Pisin" },
    { mp4v2::impl::bmff::ILC_TSI,  "tsi",  "Tsimshian" },
    { mp4v2::impl::bmff::ILC_TSN,  "tsn",  "Tswana" },
    { mp4v2::impl::bmff::ILC_TSO,  "tso",  "Tsonga" },
    { mp4v2::impl::bmff::ILC_TUK,  "tuk",  "Turkmen" },
    { mp4v2::impl::bmff::ILC_TUM,  "tum",  "Tumbuka" },
    { mp4v2::impl::bmff::ILC_TUP,  "tup",  "Tupi languages" },
    { mp4v2::impl::bmff::ILC_TUR,  "tur",  "Turkish" },
    { mp4v2::impl::bmff::ILC_TUT,  "tut",  "Altaic (Other)" },
    { mp4v2::impl::bmff::ILC_TVL,  "tvl",  "Tuvalu" },
    { mp4v2::impl::bmff::ILC_TWI,  "twi",  "Twi" },
    { mp4v2::impl::bmff::ILC_TYV,  "tyv",  "Tuvinian" },
    { mp4v2::impl::bmff::ILC_UDM,  "udm",  "Udmurt" },
    { mp4v2::impl::bmff::ILC_UGA,  "uga",  "Ugaritic" },
    { mp4v2::impl::bmff::ILC_UIG,  "uig",  "Uighur; Uyghur" },
    { mp4v2::impl::bmff::ILC_UKR,  "ukr",  "Ukrainian" },
    { mp4v2::impl::bmff::ILC_UMB,  "umb",  "Umbundu" },
    { mp4v2::impl::bmff::ILC_UND,  "und",  "Undetermined" },
    { mp4v2::impl::bmff::ILC_URD,  "urd",  "Urdu" },
    { mp4v2::impl::bmff::ILC_UZB,  "uzb",  "Uzbek" },
    { mp4v2::impl::bmff::ILC_VAI,  "vai",  "Vai" },
    { mp4v2::impl::bmff::ILC_VEN,  "ven",  "Venda" },
    { mp4v2::impl::bmff::ILC_VIE,  "vie",  "Vietnamese" },
    { mp4v2::impl::bmff::ILC_VOL,  "vol",  "Volapük" },
    { mp4v2::impl::bmff::ILC_VOT,  "vot",  "Votic" },
    { mp4v2::impl::bmff::ILC_WAK,  "wak",  "Wakashan languages" },
    { mp4v2::impl::bmff::ILC_WAL,  "wal",  "Walamo" },
    { mp4v2::impl::bmff::ILC_WAR,  "war",  "Waray" },
    { mp4v2::impl::bmff::ILC_WAS,  "was",  "Washo" },
    { mp4v2::impl::bmff::ILC_CYM,  "cym",  "Welsh" },
    { mp4v2::impl::bmff::ILC_WEN,  "wen",  "Sorbian languages" },
    { mp4v2::impl::bmff::ILC_WLN,  "wln",  "Walloon" },
    { mp4v2::impl::bmff::ILC_WOL,  "wol",  "Wolof" },
    { mp4v2::impl::bmff::ILC_XAL,  "xal",  "Kalmyk; Oirat" },
    { mp4v2::impl::bmff::ILC_XHO,  "xho",  "Xhosa" },
    { mp4v2::impl::bmff::ILC_YAO,  "yao",  "Yao" },
    { mp4v2::impl::bmff::ILC_YAP,  "yap",  "Yapese" },
    { mp4v2::impl::bmff::ILC_YID,  "yid",  "Yiddish" },
    { mp4v2::impl::bmff::ILC_YOR,  "yor",  "Yoruba" },
    { mp4v2::impl::bmff::ILC_YPK,  "ypk",  "Yupik languages" },
    { mp4v2::impl::bmff::ILC_ZAP,  "zap",  "Zapotec" },
    { mp4v2::impl::bmff::ILC_ZBL,  "zbl",  "Blissymbols; Blissymbolics; Bliss" },
    { mp4v2::impl::bmff::ILC_ZEN,  "zen",  "Zenaga" },
    { mp4v2::impl::bmff::ILC_ZHA,  "zha",  "Zhuang; Chuang" },
    { mp4v2::impl::bmff::ILC_ZND,  "znd",  "Zande languages" },
    { mp4v2::impl::bmff::ILC_ZUL,  "zul",  "Zulu" },
    { mp4v2::impl::bmff::ILC_ZUN,  "zun",  "Zuni" },
    { mp4v2::impl::bmff::ILC_ZXX,  "zxx",  "No linguistic content; Not applicable" },
    { mp4v2::impl::bmff::ILC_ZZA,  "zza",  "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki" },

    { mp4v2::impl::bmff::ILC_UNDEFINED } // must be last
};

///////////////////////////////////////////////////////////////////////////////

namespace bmff {

///////////////////////////////////////////////////////////////////////////////

// must come after static data init
const EnumLanguageCode enumLanguageCode;

///////////////////////////////////////////////////////////////////////////////

}}} // namespace mp4v2::impl::bmff
